//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_filtro_cliente
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string IdUsuario { get; set; }
        public int IdCliente { get; set; }
    }
}
