//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesCompra_reporte_Ge : DbContext
    {
        public EntitiesCompra_reporte_Ge()
            : base("name=EntitiesCompra_reporte_Ge")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCOMP_Rpt001> vwCOMP_Rpt001 { get; set; }
        public DbSet<vwCOMP_Rpt002> vwCOMP_Rpt002 { get; set; }
        public DbSet<vwCOMP_Rpt003> vwCOMP_Rpt003 { get; set; }
        public DbSet<vwCOMP_Rpt004> vwCOMP_Rpt004 { get; set; }
        public DbSet<vwCOMP_Rpt005> vwCOMP_Rpt005 { get; set; }
        public DbSet<vwCOMP_Rpt006> vwCOMP_Rpt006 { get; set; }
        public DbSet<vwCOMP_Rpt008> vwCOMP_Rpt008 { get; set; }
        public DbSet<vwCOMP_Rpt009> vwCOMP_Rpt009 { get; set; }
        public DbSet<vwCOMP_Rpt011> vwCOMP_Rpt011 { get; set; }
        public DbSet<vwCOMP_Rpt012> vwCOMP_Rpt012 { get; set; }
        public DbSet<vwCOMP_Rpt013> vwCOMP_Rpt013 { get; set; }
    
        public virtual ObjectResult<spCOMP_Rpt007_Result> spCOMP_Rpt007(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursalIni, Nullable<int> p_IdSucursalFin, Nullable<System.DateTime> p_FechaCorte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(int));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(int));
    
            var p_FechaCorteParameter = p_FechaCorte.HasValue ?
                new ObjectParameter("p_FechaCorte", p_FechaCorte) :
                new ObjectParameter("p_FechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCOMP_Rpt007_Result>("spCOMP_Rpt007", p_IdEmpresaParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_FechaCorteParameter);
        }
    
        public virtual ObjectResult<spCOMP_Rpt010_Result> spCOMP_Rpt010(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<int> p_IdProveedor, string p_IdCentroCosto, Nullable<System.DateTime> p_Fecha_Desde, Nullable<System.DateTime> p_Fecha_Hasta, Nullable<bool> p_MostrarConSaldo, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_IdProveedorParameter = p_IdProveedor.HasValue ?
                new ObjectParameter("p_IdProveedor", p_IdProveedor) :
                new ObjectParameter("p_IdProveedor", typeof(int));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_Fecha_DesdeParameter = p_Fecha_Desde.HasValue ?
                new ObjectParameter("p_Fecha_Desde", p_Fecha_Desde) :
                new ObjectParameter("p_Fecha_Desde", typeof(System.DateTime));
    
            var p_Fecha_HastaParameter = p_Fecha_Hasta.HasValue ?
                new ObjectParameter("p_Fecha_Hasta", p_Fecha_Hasta) :
                new ObjectParameter("p_Fecha_Hasta", typeof(System.DateTime));
    
            var p_MostrarConSaldoParameter = p_MostrarConSaldo.HasValue ?
                new ObjectParameter("p_MostrarConSaldo", p_MostrarConSaldo) :
                new ObjectParameter("p_MostrarConSaldo", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCOMP_Rpt010_Result>("spCOMP_Rpt010", p_IdEmpresaParameter, p_IdSucursalParameter, p_IdProveedorParameter, p_IdCentroCostoParameter, p_Fecha_DesdeParameter, p_Fecha_HastaParameter, p_MostrarConSaldoParameter, p_IdUsuarioParameter);
        }
    }
}
