//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesFacturacion_Reportes : DbContext
    {
        public EntitiesFacturacion_Reportes()
            : base("name=EntitiesFacturacion_Reportes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwFAC_Rpt003> vwFAC_Rpt003 { get; set; }
        public DbSet<vwFAC_Rpt005> vwFAC_Rpt005 { get; set; }
        public DbSet<vwFAC_Rpt006> vwFAC_Rpt006 { get; set; }
        public DbSet<vwFAC_Rpt007> vwFAC_Rpt007 { get; set; }
        public DbSet<vwFAC_Rpt009> vwFAC_Rpt009 { get; set; }
        public DbSet<vwFAC_Rpt010> vwFAC_Rpt010 { get; set; }
        public DbSet<vwFAC_Rpt011> vwFAC_Rpt011 { get; set; }
        public DbSet<vwFAC_Rpt012> vwFAC_Rpt012 { get; set; }
        public DbSet<vwFAC_Rpt013> vwFAC_Rpt013 { get; set; }
        public DbSet<vwFAC_Rpt001> vwFAC_Rpt001 { get; set; }
        public DbSet<vwFAC_Rpt004> vwFAC_Rpt004 { get; set; }
        public DbSet<vwFAC_Rpt004_Detalle> vwFAC_Rpt004_Detalle { get; set; }
        public DbSet<vwFAC_Rpt008> vwFAC_Rpt008 { get; set; }
        public DbSet<vwFAC_Rpt002> vwFAC_Rpt002 { get; set; }
        public DbSet<vwFAC_EDEHSA_Rpt001> vwFAC_EDEHSA_Rpt001 { get; set; }
        public DbSet<fa_filtro_cliente> fa_filtro_cliente { get; set; }
    
        public virtual ObjectResult<spFAC_Rpt013_Result> spFAC_Rpt013(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdCliente, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdClienteParameter = p_IdCliente.HasValue ?
                new ObjectParameter("p_IdCliente", p_IdCliente) :
                new ObjectParameter("p_IdCliente", typeof(decimal));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_Rpt013_Result>("spFAC_Rpt013", p_IdEmpresaParameter, p_IdClienteParameter, p_FechaIniParameter, p_FechaFinParameter);
        }
    
        public virtual ObjectResult<spFAC_Rpt015_Result> spFAC_Rpt015(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdClienteIni, Nullable<decimal> p_IdClienteFin, Nullable<decimal> p_IdSucursalIni, Nullable<decimal> p_IdSucursalFin, Nullable<decimal> p_IdBodegaIni, Nullable<decimal> p_IdBodegaFin, Nullable<decimal> p_IdVendedorIni, Nullable<decimal> p_IdVendedorFin, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdClienteIniParameter = p_IdClienteIni.HasValue ?
                new ObjectParameter("p_IdClienteIni", p_IdClienteIni) :
                new ObjectParameter("p_IdClienteIni", typeof(decimal));
    
            var p_IdClienteFinParameter = p_IdClienteFin.HasValue ?
                new ObjectParameter("p_IdClienteFin", p_IdClienteFin) :
                new ObjectParameter("p_IdClienteFin", typeof(decimal));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(decimal));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(decimal));
    
            var p_IdBodegaIniParameter = p_IdBodegaIni.HasValue ?
                new ObjectParameter("p_IdBodegaIni", p_IdBodegaIni) :
                new ObjectParameter("p_IdBodegaIni", typeof(decimal));
    
            var p_IdBodegaFinParameter = p_IdBodegaFin.HasValue ?
                new ObjectParameter("p_IdBodegaFin", p_IdBodegaFin) :
                new ObjectParameter("p_IdBodegaFin", typeof(decimal));
    
            var p_IdVendedorIniParameter = p_IdVendedorIni.HasValue ?
                new ObjectParameter("p_IdVendedorIni", p_IdVendedorIni) :
                new ObjectParameter("p_IdVendedorIni", typeof(decimal));
    
            var p_IdVendedorFinParameter = p_IdVendedorFin.HasValue ?
                new ObjectParameter("p_IdVendedorFin", p_IdVendedorFin) :
                new ObjectParameter("p_IdVendedorFin", typeof(decimal));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_Rpt015_Result>("spFAC_Rpt015", p_IdEmpresaParameter, p_IdClienteIniParameter, p_IdClienteFinParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_IdBodegaIniParameter, p_IdBodegaFinParameter, p_IdVendedorIniParameter, p_IdVendedorFinParameter, p_FechaIniParameter, p_FechaFinParameter);
        }
    
        public virtual ObjectResult<spFAC_CostoProductoVendido_Result> spFAC_CostoProductoVendido(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_CostoProductoVendido_Result>("spFAC_CostoProductoVendido", p_IdEmpresaParameter, p_IdSucursalParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spFAC_Rpt014_Result> spFAC_Rpt014(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_Rpt014_Result>("spFAC_Rpt014", p_IdEmpresaParameter, p_IdSucursalParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spFAC_Rpt016_Result> spFAC_Rpt016(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFAC_Rpt016_Result>("spFAC_Rpt016", p_IdEmpresaParameter, p_IdSucursalParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdUsuarioParameter);
        }
    }
}
