//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_CuentasxCobrar : DbContext
    {
        public Entities_CuentasxCobrar()
            : base("name=Entities_CuentasxCobrar")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCXC_Rpt002> vwCXC_Rpt002 { get; set; }
        public DbSet<vwCXC_Rpt003> vwCXC_Rpt003 { get; set; }
        public DbSet<vwCXC_Rpt005> vwCXC_Rpt005 { get; set; }
        public DbSet<vwCXC_Rpt011> vwCXC_Rpt011 { get; set; }
        public DbSet<vwCXC_Rpt001> vwCXC_Rpt001 { get; set; }
        public DbSet<vwCXC_Rpt014> vwCXC_Rpt014 { get; set; }
        public DbSet<vwCXC_Rpt016> vwCXC_Rpt016 { get; set; }
        public DbSet<vwCXC_Rpt013> vwCXC_Rpt013 { get; set; }
        public DbSet<vwCXC_Rpt004> vwCXC_Rpt004 { get; set; }
        public DbSet<vwCXC_Rpt006> vwCXC_Rpt006 { get; set; }
        public DbSet<vwCXC_Rpt007> vwCXC_Rpt007 { get; set; }
        public DbSet<vwCXC_Rpt019> vwCXC_Rpt019 { get; set; }
        public DbSet<vwCXC_Rpt019_1> vwCXC_Rpt019_1 { get; set; }
        public DbSet<vwCXC_Rpt019_2> vwCXC_Rpt019_2 { get; set; }
        public DbSet<vwCXC_Rpt020> vwCXC_Rpt020 { get; set; }
    
        public virtual ObjectResult<spCXC_Rpt008_Result> spCXC_Rpt008(Nullable<int> p_IdEmpresa, Nullable<int> p_SucursalIni, Nullable<int> p_SucursalFin, Nullable<System.DateTime> p_fechaCorte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_SucursalIniParameter = p_SucursalIni.HasValue ?
                new ObjectParameter("p_SucursalIni", p_SucursalIni) :
                new ObjectParameter("p_SucursalIni", typeof(int));
    
            var p_SucursalFinParameter = p_SucursalFin.HasValue ?
                new ObjectParameter("p_SucursalFin", p_SucursalFin) :
                new ObjectParameter("p_SucursalFin", typeof(int));
    
            var p_fechaCorteParameter = p_fechaCorte.HasValue ?
                new ObjectParameter("p_fechaCorte", p_fechaCorte) :
                new ObjectParameter("p_fechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt008_Result>("spCXC_Rpt008", p_IdEmpresaParameter, p_SucursalIniParameter, p_SucursalFinParameter, p_fechaCorteParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt010_Result> spCXC_Rpt010(Nullable<int> p_IdEmpresa, Nullable<int> p_SucursalIni, Nullable<int> p_SucursalFin, Nullable<System.DateTime> p_fechaCorte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_SucursalIniParameter = p_SucursalIni.HasValue ?
                new ObjectParameter("p_SucursalIni", p_SucursalIni) :
                new ObjectParameter("p_SucursalIni", typeof(int));
    
            var p_SucursalFinParameter = p_SucursalFin.HasValue ?
                new ObjectParameter("p_SucursalFin", p_SucursalFin) :
                new ObjectParameter("p_SucursalFin", typeof(int));
    
            var p_fechaCorteParameter = p_fechaCorte.HasValue ?
                new ObjectParameter("p_fechaCorte", p_fechaCorte) :
                new ObjectParameter("p_fechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt010_Result>("spCXC_Rpt010", p_IdEmpresaParameter, p_SucursalIniParameter, p_SucursalFinParameter, p_fechaCorteParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt009_Result> spCXC_Rpt009(Nullable<int> p_IdEmpresa, Nullable<int> p_SucursalIni, Nullable<int> p_SucursalFin, Nullable<System.DateTime> p_fechaCorte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_SucursalIniParameter = p_SucursalIni.HasValue ?
                new ObjectParameter("p_SucursalIni", p_SucursalIni) :
                new ObjectParameter("p_SucursalIni", typeof(int));
    
            var p_SucursalFinParameter = p_SucursalFin.HasValue ?
                new ObjectParameter("p_SucursalFin", p_SucursalFin) :
                new ObjectParameter("p_SucursalFin", typeof(int));
    
            var p_fechaCorteParameter = p_fechaCorte.HasValue ?
                new ObjectParameter("p_fechaCorte", p_fechaCorte) :
                new ObjectParameter("p_fechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt009_Result>("spCXC_Rpt009", p_IdEmpresaParameter, p_SucursalIniParameter, p_SucursalFinParameter, p_fechaCorteParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt007_Result> spCXC_Rpt007(Nullable<int> p_IdEmpresa, Nullable<int> p_SucursalIni, Nullable<int> p_SucursalFin, Nullable<decimal> p_IdCliente, Nullable<System.DateTime> p_fechaCorte, Nullable<bool> p_solo_cbtes_con_saldo)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_SucursalIniParameter = p_SucursalIni.HasValue ?
                new ObjectParameter("p_SucursalIni", p_SucursalIni) :
                new ObjectParameter("p_SucursalIni", typeof(int));
    
            var p_SucursalFinParameter = p_SucursalFin.HasValue ?
                new ObjectParameter("p_SucursalFin", p_SucursalFin) :
                new ObjectParameter("p_SucursalFin", typeof(int));
    
            var p_IdClienteParameter = p_IdCliente.HasValue ?
                new ObjectParameter("p_IdCliente", p_IdCliente) :
                new ObjectParameter("p_IdCliente", typeof(decimal));
    
            var p_fechaCorteParameter = p_fechaCorte.HasValue ?
                new ObjectParameter("p_fechaCorte", p_fechaCorte) :
                new ObjectParameter("p_fechaCorte", typeof(System.DateTime));
    
            var p_solo_cbtes_con_saldoParameter = p_solo_cbtes_con_saldo.HasValue ?
                new ObjectParameter("p_solo_cbtes_con_saldo", p_solo_cbtes_con_saldo) :
                new ObjectParameter("p_solo_cbtes_con_saldo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt007_Result>("spCXC_Rpt007", p_IdEmpresaParameter, p_SucursalIniParameter, p_SucursalFinParameter, p_IdClienteParameter, p_fechaCorteParameter, p_solo_cbtes_con_saldoParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt012_Result> spCXC_Rpt012(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdCliente, Nullable<System.DateTime> p_fechaCorte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdClienteParameter = p_IdCliente.HasValue ?
                new ObjectParameter("p_IdCliente", p_IdCliente) :
                new ObjectParameter("p_IdCliente", typeof(decimal));
    
            var p_fechaCorteParameter = p_fechaCorte.HasValue ?
                new ObjectParameter("p_fechaCorte", p_fechaCorte) :
                new ObjectParameter("p_fechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt012_Result>("spCXC_Rpt012", p_IdEmpresaParameter, p_IdClienteParameter, p_fechaCorteParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt015_Result> spCXC_Rpt015(Nullable<int> p_IdEmpresa, Nullable<int> p_SucursalIni, Nullable<int> p_SucursalFin, Nullable<System.DateTime> p_fechaIni, Nullable<System.DateTime> p_fechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_SucursalIniParameter = p_SucursalIni.HasValue ?
                new ObjectParameter("p_SucursalIni", p_SucursalIni) :
                new ObjectParameter("p_SucursalIni", typeof(int));
    
            var p_SucursalFinParameter = p_SucursalFin.HasValue ?
                new ObjectParameter("p_SucursalFin", p_SucursalFin) :
                new ObjectParameter("p_SucursalFin", typeof(int));
    
            var p_fechaIniParameter = p_fechaIni.HasValue ?
                new ObjectParameter("p_fechaIni", p_fechaIni) :
                new ObjectParameter("p_fechaIni", typeof(System.DateTime));
    
            var p_fechaFinParameter = p_fechaFin.HasValue ?
                new ObjectParameter("p_fechaFin", p_fechaFin) :
                new ObjectParameter("p_fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt015_Result>("spCXC_Rpt015", p_IdEmpresaParameter, p_SucursalIniParameter, p_SucursalFinParameter, p_fechaIniParameter, p_fechaFinParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt021_Result> spCXC_Rpt021(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<decimal> p_IdCliente)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_IdClienteParameter = p_IdCliente.HasValue ?
                new ObjectParameter("p_IdCliente", p_IdCliente) :
                new ObjectParameter("p_IdCliente", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt021_Result>("spCXC_Rpt021", p_IdEmpresaParameter, p_IdSucursalParameter, p_IdClienteParameter);
        }
    
        public virtual ObjectResult<spCXC_Rpt017_Result> spCXC_Rpt017(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_Rpt017_Result>("spCXC_Rpt017", p_IdEmpresaParameter, p_FechaIniParameter, p_FechaFinParameter);
        }
    }
}
