//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesConta_General : DbContext
    {
        public EntitiesConta_General()
            : base("name=EntitiesConta_General")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCONTA_Rpt001> vwCONTA_Rpt001 { get; set; }
        public DbSet<vwCONTA_Rpt002> vwCONTA_Rpt002 { get; set; }
        public DbSet<vwCONTA_Rpt003> vwCONTA_Rpt003 { get; set; }
    }
}
