//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesBancos_Reporte_Ge : DbContext
    {
        public EntitiesBancos_Reporte_Ge()
            : base("name=EntitiesBancos_Reporte_Ge")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwba_Cbte_Ban> vwba_Cbte_Ban { get; set; }
        public DbSet<vwBAN_Rpt001> vwBAN_Rpt001 { get; set; }
        public DbSet<vwBAN_Rpt002> vwBAN_Rpt002 { get; set; }
        public DbSet<vwBAN_Rpt003> vwBAN_Rpt003 { get; set; }
        public DbSet<vwBAN_Rpt004> vwBAN_Rpt004 { get; set; }
        public DbSet<vwBAN_Rpt005> vwBAN_Rpt005 { get; set; }
        public DbSet<vwBAN_Rpt006> vwBAN_Rpt006 { get; set; }
        public DbSet<vwBAN_Rpt007> vwBAN_Rpt007 { get; set; }
        public DbSet<vwBAN_Rpt010> vwBAN_Rpt010 { get; set; }
        public DbSet<vwBAN_Rpt011> vwBAN_Rpt011 { get; set; }
        public DbSet<vwBAN_Rpt012> vwBAN_Rpt012 { get; set; }
        public DbSet<vwBAN_Rpt013> vwBAN_Rpt013 { get; set; }
        public DbSet<vwBAN_Rpt014> vwBAN_Rpt014 { get; set; }
        public DbSet<vwBAN_Rpt015> vwBAN_Rpt015 { get; set; }
        public DbSet<vwBAN_Rpt016> vwBAN_Rpt016 { get; set; }
        public DbSet<vwBAN_Rpt018> vwBAN_Rpt018 { get; set; }
        public DbSet<vwBAN_Rpt019> vwBAN_Rpt019 { get; set; }
    
        public virtual ObjectResult<spBAN_Rpt008_Result> spBAN_Rpt008(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fecha_Ini, Nullable<System.DateTime> p_fecha_Fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fecha_IniParameter = p_fecha_Ini.HasValue ?
                new ObjectParameter("p_fecha_Ini", p_fecha_Ini) :
                new ObjectParameter("p_fecha_Ini", typeof(System.DateTime));
    
            var p_fecha_FinParameter = p_fecha_Fin.HasValue ?
                new ObjectParameter("p_fecha_Fin", p_fecha_Fin) :
                new ObjectParameter("p_fecha_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt008_Result>("spBAN_Rpt008", p_IdEmpresaParameter, p_fecha_IniParameter, p_fecha_FinParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt011_Result> spBAN_Rpt011(Nullable<int> p_IdEmpresa, Nullable<int> p_IdBanco, Nullable<decimal> p_IdConciliacion)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdBancoParameter = p_IdBanco.HasValue ?
                new ObjectParameter("p_IdBanco", p_IdBanco) :
                new ObjectParameter("p_IdBanco", typeof(int));
    
            var p_IdConciliacionParameter = p_IdConciliacion.HasValue ?
                new ObjectParameter("p_IdConciliacion", p_IdConciliacion) :
                new ObjectParameter("p_IdConciliacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt011_Result>("spBAN_Rpt011", p_IdEmpresaParameter, p_IdBancoParameter, p_IdConciliacionParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt007_saldos_Result> spBAN_Rpt007_saldos(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt007_saldos_Result>("spBAN_Rpt007_saldos", p_IdEmpresaParameter, p_Fecha_iniParameter, p_Fecha_finParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt010_Result> spBAN_Rpt010(Nullable<int> p_IdEmpresa, Nullable<int> p_IdBanco, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdBancoParameter = p_IdBanco.HasValue ?
                new ObjectParameter("p_IdBanco", p_IdBanco) :
                new ObjectParameter("p_IdBanco", typeof(int));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt010_Result>("spBAN_Rpt010", p_IdEmpresaParameter, p_IdBancoParameter, p_Fecha_iniParameter, p_Fecha_finParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt007_Result> spBAN_Rpt007(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fecha_Ini, Nullable<System.DateTime> p_fecha_Fin, Nullable<int> p_IdTipoFlujo_ini, Nullable<int> p_IdTipoFlujo_fin, Nullable<int> p_IdBanco_ini, Nullable<int> p_IdBanco_fin, Nullable<bool> p_Mostrar_detallado, Nullable<bool> p_Mostrar_registros_en_conciliacion)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fecha_IniParameter = p_fecha_Ini.HasValue ?
                new ObjectParameter("p_fecha_Ini", p_fecha_Ini) :
                new ObjectParameter("p_fecha_Ini", typeof(System.DateTime));
    
            var p_fecha_FinParameter = p_fecha_Fin.HasValue ?
                new ObjectParameter("p_fecha_Fin", p_fecha_Fin) :
                new ObjectParameter("p_fecha_Fin", typeof(System.DateTime));
    
            var p_IdTipoFlujo_iniParameter = p_IdTipoFlujo_ini.HasValue ?
                new ObjectParameter("p_IdTipoFlujo_ini", p_IdTipoFlujo_ini) :
                new ObjectParameter("p_IdTipoFlujo_ini", typeof(int));
    
            var p_IdTipoFlujo_finParameter = p_IdTipoFlujo_fin.HasValue ?
                new ObjectParameter("p_IdTipoFlujo_fin", p_IdTipoFlujo_fin) :
                new ObjectParameter("p_IdTipoFlujo_fin", typeof(int));
    
            var p_IdBanco_iniParameter = p_IdBanco_ini.HasValue ?
                new ObjectParameter("p_IdBanco_ini", p_IdBanco_ini) :
                new ObjectParameter("p_IdBanco_ini", typeof(int));
    
            var p_IdBanco_finParameter = p_IdBanco_fin.HasValue ?
                new ObjectParameter("p_IdBanco_fin", p_IdBanco_fin) :
                new ObjectParameter("p_IdBanco_fin", typeof(int));
    
            var p_Mostrar_detalladoParameter = p_Mostrar_detallado.HasValue ?
                new ObjectParameter("p_Mostrar_detallado", p_Mostrar_detallado) :
                new ObjectParameter("p_Mostrar_detallado", typeof(bool));
    
            var p_Mostrar_registros_en_conciliacionParameter = p_Mostrar_registros_en_conciliacion.HasValue ?
                new ObjectParameter("p_Mostrar_registros_en_conciliacion", p_Mostrar_registros_en_conciliacion) :
                new ObjectParameter("p_Mostrar_registros_en_conciliacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt007_Result>("spBAN_Rpt007", p_IdEmpresaParameter, p_fecha_IniParameter, p_fecha_FinParameter, p_IdTipoFlujo_iniParameter, p_IdTipoFlujo_finParameter, p_IdBanco_iniParameter, p_IdBanco_finParameter, p_Mostrar_detalladoParameter, p_Mostrar_registros_en_conciliacionParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt009_1_Result> spBAN_Rpt009_1(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_fecha_fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_fecha_finParameter = p_fecha_fin.HasValue ?
                new ObjectParameter("p_fecha_fin", p_fecha_fin) :
                new ObjectParameter("p_fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt009_1_Result>("spBAN_Rpt009_1", p_IdEmpresaParameter, p_Fecha_iniParameter, p_fecha_finParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt009_Result> spBAN_Rpt009(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_fecha_fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_fecha_finParameter = p_fecha_fin.HasValue ?
                new ObjectParameter("p_fecha_fin", p_fecha_fin) :
                new ObjectParameter("p_fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt009_Result>("spBAN_Rpt009", p_IdEmpresaParameter, p_Fecha_iniParameter, p_fecha_finParameter);
        }
    }
}
