//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACTF_Rpt014_1
    {
        public int IdEmpresa { get; set; }
        public int IdActivoFijo { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public string CodActivoFijo { get; set; }
        public string Af_Nombre { get; set; }
        public int IdActijoFijoTipo { get; set; }
        public string Af_Descripcion { get; set; }
        public int IdCategoriaAF { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Depreciacion { get; set; }
        public System.DateTime Af_fecha_compra { get; set; }
        public System.DateTime Af_fecha_ini_depre { get; set; }
        public System.DateTime Af_fecha_fin_depre { get; set; }
        public Nullable<double> Af_costo_compra { get; set; }
        public Nullable<double> Af_ValorResidual { get; set; }
        public Nullable<double> ActivoNeto { get; set; }
        public Nullable<double> DepAnioAnt { get; set; }
        public Nullable<double> DepAnioAct { get; set; }
        public Nullable<double> ValorMensual { get; set; }
        public Nullable<double> DepAcum { get; set; }
        public Nullable<double> TotlDep { get; set; }
        public Nullable<double> ValorLibros { get; set; }
        public decimal IdDepreciacion { get; set; }
    }
}
