//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwACTF_Rpt016
    {
        public int IdEmpresa { get; set; }
        public int IdActivoFijo { get; set; }
        public string CodActivoFijo { get; set; }
        public string Af_Codigo_Barra { get; set; }
        public string Af_Nombre { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string nom_departamento { get; set; }
        public Nullable<decimal> IdEncargado { get; set; }
        public string nom_encargado { get; set; }
        public Nullable<decimal> IdOrdenCompra { get; set; }
        public System.DateTime Af_fecha_compra { get; set; }
        public string num_factura { get; set; }
    }
}
