//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBAN_Rpt011
    {
        public int IdEmpresa { get; set; }
        public decimal IdConciliacion { get; set; }
        public int IdBanco { get; set; }
        public int IdPeriodo { get; set; }
        public string nom_banco { get; set; }
        public string ba_Num_Cuenta { get; set; }
        public string IdCtaCble { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodTipoCbte { get; set; }
        public string Tipo_Cbte { get; set; }
        public double Valor { get; set; }
        public string Observacion { get; set; }
        public string Cheque { get; set; }
        public string ruc_empresa { get; set; }
        public string nom_empresa { get; set; }
    }
}
