//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCOMP_Rpt009
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdSolicitudCompra { get; set; }
        public string Sucursal { get; set; }
        public System.DateTime fecha { get; set; }
        public int plazo { get; set; }
        public System.DateTime fecha_vtc { get; set; }
        public string observacion { get; set; }
        public string Estado { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public string nom_EstadoAprobacion { get; set; }
        public decimal IdPersona_Solicita { get; set; }
        public string Solicitante { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string nom_proyecto { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string cod_producto { get; set; }
        public string NomProducto { get; set; }
        public double Cantidad_Solicitada { get; set; }
        public double Cantidad_Comprada { get; set; }
        public double Cantidad_Pendiente { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdUnidadMedida { get; set; }
        public string nom_Unidad { get; set; }
        public string nom_Unidad_Alterno { get; set; }
        public string do_observacion { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public string Descripcion_Oferta { get; set; }
        public Nullable<int> Secuencia_Oferta { get; set; }
        public string cod_rubro { get; set; }
        public string nom_rubro { get; set; }
    }
}
