//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXC_Rpt019_2
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public string CodDocumentoTipo { get; set; }
        public string CodNota { get; set; }
        public string serie1 { get; set; }
        public string serie2 { get; set; }
        public string NumNota_Impresa { get; set; }
        public Nullable<double> CobroTotal { get; set; }
        public Nullable<System.DateTime> fechaUltimoCobro { get; set; }
    }
}
