//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_Rpt039
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_codigo_barra { get; set; }
        public string IdCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string TipoDocumento { get; set; }
        public string numDocumento { get; set; }
        public Nullable<decimal> IdOrdenCompra { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string Proveedor { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public string cm_observacion { get; set; }
        public string Ubicacion1 { get; set; }
        public string Ubicacion2 { get; set; }
    }
}
