//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bizu.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-ES&quot;&gt;
        ///  &lt;Title Text=&quot;Tablero de control&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;localhost_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///          &lt;Parameter Nam [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_01 {
            get {
                return ResourceManager.GetString("dashboard_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-ES&quot;&gt;
        ///  &lt;Title Text=&quot;Tablero de control&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///     &lt;Connection Name=&quot;localhost_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///          &lt;Parameter Name [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_02 {
            get {
                return ResourceManager.GetString("dashboard_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-ES&quot;&gt;
        ///  &lt;Title Text=&quot;Dashboard Guía Remisión&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;localhost_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///          &lt;Paramete [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_03 {
            get {
                return ResourceManager.GetString("dashboard_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-EC&quot;&gt;
        ///  &lt;Title Text=&quot;Tablero de control&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 2&quot; ComponentName=&quot;dashboardSqlDataSource2&quot;&gt;
        ///      &lt;Connection Name=&quot;localhost_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///          &lt;Parameter Nam [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_OT {
            get {
                return ResourceManager.GetString("dashboard_OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-EC&quot;&gt;
        ///  &lt;Title Text=&quot;Tablero de Ordenes de Taller por Motivo de Anulación&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;localhost_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Valu [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_OT_Anulaciones {
            get {
                return ResourceManager.GetString("dashboard_OT_Anulaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;es-EC&quot;&gt;
        ///  &lt;Title Text=&quot;Tablero de control&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;SqlDataSource Name=&quot;Origen de datos SQL 1&quot; ComponentName=&quot;dashboardSqlDataSource1&quot;&gt;
        ///      &lt;Connection Name=&quot;10.0.0.11_DBERP_PRODUCCION_Connection&quot; ProviderKey=&quot;MySql&quot;&gt;
        ///        &lt;Parameters&gt;
        ///          &lt;Parameter Name=&quot;server&quot; Value=&quot;10.0.0.11&quot; /&gt;
        ///          &lt;Parameter Name=&quot;database&quot; Value=&quot;DBERP_PRODUCCION&quot; /&gt;
        ///          &lt;Parameter Name=&quot;read only&quot; Value=&quot;1&quot; /&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string dashboard_produccion {
            get {
                return ResourceManager.GetString("dashboard_produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon Dazzsoft_3D_Icon {
            get {
                object obj = ResourceManager.GetObject("Dazzsoft_3D_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap erp_256 {
            get {
                object obj = ResourceManager.GetObject("erp_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] EstadoCta_Banco_Gye_Demo {
            get {
                object obj = ResourceManager.GetObject("EstadoCta_Banco_Gye_Demo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_dazzsoft_3d {
            get {
                object obj = ResourceManager.GetObject("logo dazzsoft 3d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Activo_Fijo_Ejemplo {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Activo_Fijo_Ejemplo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Consolidado_IESS {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Consolidado_IESS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_diario {
            get {
                object obj = ResourceManager.GetObject("Plantilla_diario", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_Alumno {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_Alumno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_Clientes {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_Clientes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_CXC_ND_Saldo_inicial {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_CXC_ND_Saldo_inicial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_CXC_ND_Saldo_inicial_x_Estudiante_CAH {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_CXC_ND_Saldo_inicial_x_Estudiante_CAH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_ND_Saldo_inicial_CXP {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_ND_Saldo_inicial_CXP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_Productos {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_Productos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Ejemplo_Proveedores {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Ejemplo_Proveedores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Empleados {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Empleados", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_inventario {
            get {
                object obj = ResourceManager.GetObject("Plantilla_inventario", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_oferta {
            get {
                object obj = ResourceManager.GetObject("Plantilla_oferta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Oferta_Ejemplo {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Oferta_Ejemplo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Plan_de_Ctas_itCorp {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Plan_de_Ctas_itCorp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_Recosteo {
            get {
                object obj = ResourceManager.GetObject("Plantilla_Recosteo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] Plantilla_respuesta_colecturia {
            get {
                object obj = ResourceManager.GetObject("Plantilla_respuesta_colecturia", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
