//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_notaCreDeb_x_in_Ing_Egr_Inven
    {
        public int no_IdEmpresa { get; set; }
        public int no_IdSucursal { get; set; }
        public int no_IdBodega { get; set; }
        public decimal no_IdNota { get; set; }
        public int in_IdEmpresa { get; set; }
        public int in_IdSucursal { get; set; }
        public int in_IdMovi_inven_tipo { get; set; }
        public decimal in_IdNumMovi { get; set; }
    
        public virtual fa_notaCreDeb fa_notaCreDeb { get; set; }
    }
}
