//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_anticipo_facturado
    {
        public cxc_anticipo_facturado()
        {
            this.cxc_anticipo_facturado_det = new HashSet<cxc_anticipo_facturado_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdAnticipo { get; set; }
        public decimal IdCliente { get; set; }
        public int IdProyecto { get; set; }
        public int IdOferta { get; set; }
        public string IdCentroCosto { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEmpresa_ct { get; set; }
        public Nullable<int> IdTipoCbte_ct { get; set; }
        public Nullable<decimal> IdCbteCble_ct { get; set; }
        public Nullable<int> IdEmpresa_CbteVta { get; set; }
        public Nullable<int> IdSucursal_CbteVta { get; set; }
        public Nullable<int> IdBodega_CbteVta { get; set; }
        public Nullable<decimal> IdCbteVta { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<cxc_anticipo_facturado_det> cxc_anticipo_facturado_det { get; set; }
    }
}
