//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_anticipo_facturado_det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdAnticipo { get; set; }
        public int Secuencia { get; set; }
        public string Detalle { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Valor { get; set; }
        public Nullable<int> IdEmpresa_ct { get; set; }
        public Nullable<int> IdTipoCbte_ct { get; set; }
        public Nullable<decimal> IdCbteCble_ct { get; set; }
        public string IdCtaCble { get; set; }
    
        public virtual cxc_anticipo_facturado cxc_anticipo_facturado { get; set; }
    }
}
