//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cobros_Pendientes_de_deposito
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public string cr_Codigo { get; set; }
        public string IdCobro_tipo { get; set; }
        public decimal IdCliente { get; set; }
        public double cr_TotalCobro { get; set; }
        public string cr_fecha { get; set; }
        public string cr_fechaDocu { get; set; }
        public string cr_fechaCobro { get; set; }
        public string cr_observacion { get; set; }
        public string cr_estado { get; set; }
        public int CompCobro_IdTipoCbte { get; set; }
        public decimal CompCobro_IdCbteCble { get; set; }
        public string CompCobro_cb_Fecha { get; set; }
        public double CompCobro_Valor { get; set; }
        public Nullable<int> Deposito_IdTipocbte { get; set; }
        public Nullable<decimal> Deposito_IdCbteCble { get; set; }
    }
}
