//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_GuiaRemision_Motivo
    {
        public in_GuiaRemision_Motivo()
        {
            this.in_GuiaRemision = new HashSet<in_GuiaRemision>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdMotivo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<in_GuiaRemision> in_GuiaRemision { get; set; }
    }
}
