//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Marca
    {
        public in_Marca()
        {
            this.in_Marca_filtro = new HashSet<in_Marca_filtro>();
            this.in_Producto = new HashSet<in_Producto>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdMarca { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
    
        public virtual ICollection<in_Marca_filtro> in_Marca_filtro { get; set; }
        public virtual ICollection<in_Producto> in_Producto { get; set; }
    }
}
