//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_movi_inve_detalle_x_item_ingresos
    {
        public Nullable<int> IdEmpresa_oc { get; set; }
        public Nullable<int> IdSucursal_oc { get; set; }
        public Nullable<decimal> IdOrdenCompra { get; set; }
        public Nullable<int> Secuencia_oc { get; set; }
        public decimal IdProducto { get; set; }
        public double dm_cantidad { get; set; }
        public double dm_precio { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string oc_NumDocumento { get; set; }
        public string codigo_reg { get; set; }
        public double cantidad { get; set; }
        public int IdEmpresa_ing { get; set; }
        public int IdSucursal_ing { get; set; }
        public int IdBodega_ing { get; set; }
        public int IdMovi_inven_tipo_ing { get; set; }
        public decimal IdNumMovi_ing { get; set; }
        public int Secuencia_ing { get; set; }
        public Nullable<System.DateTime> oc_fecha { get; set; }
    }
}
