//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Contabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp_DIARIO
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipoCbte { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public string cb_Observacion { get; set; }
        public string referencia { get; set; }
        public string tc_TipoCbte { get; set; }
        public Nullable<double> Valor_Cbte { get; set; }
        public double Valor_Cancelado_cbte { get; set; }
        public Nullable<double> Valor_saldo_cbte { get; set; }
        public string Tipo { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
    }
}
