//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_retencion_Multiple_Documentos_ValorAplicado
    {
        public int IdEmpresa { get; set; }
        public int IdMultir { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdCobro { get; set; }
        public int IdEmpresa_cbteVta { get; set; }
        public int IdSucursal_cbteVta { get; set; }
        public int IdBodega_cbteVta { get; set; }
        public decimal IdCbteVta_cbteVta { get; set; }
        public string IdTipoDoc_cbteVta { get; set; }
        public string IdCobro_tipo { get; set; }
        public double Base { get; set; }
        public double PorcentajeRetenc { get; set; }
        public double ValorRetenc { get; set; }
    
        public virtual cxc_retencion_Multiple cxc_retencion_Multiple { get; set; }
    }
}
