//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_notaCreDeb_det
    {
        public fa_notaCreDeb_det()
        {
            this.fa_notaCreDeb_det_x_in_Ing_Egr_Inven_det = new HashSet<fa_notaCreDeb_det_x_in_Ing_Egr_Inven_det>();
            this.fa_orden_Desp_det_x_in_Ing_Egr_Inven_det = new HashSet<fa_orden_Desp_det_x_in_Ing_Egr_Inven_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public double sc_cantidad { get; set; }
        public double sc_Precio { get; set; }
        public double sc_descUni { get; set; }
        public double sc_PordescUni { get; set; }
        public double sc_precioFinal { get; set; }
        public double sc_subtotal { get; set; }
        public double sc_iva { get; set; }
        public double sc_total { get; set; }
        public double sc_costo { get; set; }
        public string sc_observacion { get; set; }
        public string sc_estado { get; set; }
        public Nullable<double> sc_Peso { get; set; }
        public double vt_por_iva { get; set; }
        public Nullable<int> IdPunto_Cargo { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public string IdCod_Impuesto_Ice { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
    
        public virtual fa_notaCreDeb fa_notaCreDeb { get; set; }
        public virtual ICollection<fa_notaCreDeb_det_x_in_Ing_Egr_Inven_det> fa_notaCreDeb_det_x_in_Ing_Egr_Inven_det { get; set; }
        public virtual ICollection<fa_orden_Desp_det_x_in_Ing_Egr_Inven_det> fa_orden_Desp_det_x_in_Ing_Egr_Inven_det { get; set; }
    }
}
