//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_GuiaRemision_Det
    {
        public in_GuiaRemision_Det()
        {
            this.in_Ing_Egr_Inven_det = new HashSet<in_Ing_Egr_Inven_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdGuiaRemision { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Detalle_x_Item { get; set; }
        public double Cantidad { get; set; }
        public string IdUnidadMedida { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Cantidad_sinConversion { get; set; }
        public string IdUnidadMedida_sinConversion { get; set; }
        public string IdCentroCosto { get; set; }
    
        public virtual in_GuiaRemision in_GuiaRemision { get; set; }
        public virtual in_Producto in_Producto { get; set; }
        public virtual in_UnidadMedida in_UnidadMedida { get; set; }
        public virtual in_UnidadMedida in_UnidadMedida1 { get; set; }
        public virtual ICollection<in_Ing_Egr_Inven_det> in_Ing_Egr_Inven_det { get; set; }
    }
}
