//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Plantilla_Mensaje
    {
        public int IdEmpresa { get; set; }
        public string IdMensaje { get; set; }
        public string Mensaje { get; set; }
        public string NotificacionEntrega { get; set; }
        public string Estado { get; set; }
    }
}
