//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Inventario_Poligrup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesInventario_X_Produccion_ : DbContext
    {
        public EntitiesInventario_X_Produccion_()
            : base("name=EntitiesInventario_X_Produccion_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<in_Ing_Egr_Inven_X_Produccion> in_Ing_Egr_Inven_X_Produccion { get; set; }
        public DbSet<vwin_Ing_Egr_Inven_X_Produccion> vwin_Ing_Egr_Inven_X_Produccion { get; set; }
    }
}
