//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesCompras_GE : DbContext
    {
        public EntitiesCompras_GE()
            : base("name=EntitiesCompras_GE")
        {
        }

        //poner esta funcion dentro de la clase entities no viene por defecto
        //10000 timeout 1 minutos
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<com_catalogo> com_catalogo { get; set; }
        public DbSet<com_catalogo_tipo> com_catalogo_tipo { get; set; }
        public DbSet<com_comprador> com_comprador { get; set; }
        public DbSet<com_departamento> com_departamento { get; set; }
        public DbSet<com_estado_cierre> com_estado_cierre { get; set; }
        public DbSet<com_ListadoMateriales_Det> com_ListadoMateriales_Det { get; set; }
        public DbSet<com_Motivo_Orden_Compra> com_Motivo_Orden_Compra { get; set; }
        public DbSet<com_ordencompra_local> com_ordencompra_local { get; set; }
        public DbSet<com_ordencompra_local_det> com_ordencompra_local_det { get; set; }
        public DbSet<com_ordencompra_local_det_x_com_solicitud_compra_det> com_ordencompra_local_det_x_com_solicitud_compra_det { get; set; }
        public DbSet<com_ordencompra_local_x_com_solicitud_compra> com_ordencompra_local_x_com_solicitud_compra { get; set; }
        public DbSet<com_parametro> com_parametro { get; set; }
        public DbSet<com_solicitante> com_solicitante { get; set; }
        public DbSet<com_solicitud_compra> com_solicitud_compra { get; set; }
        public DbSet<com_solicitud_compra_det> com_solicitud_compra_det { get; set; }
        public DbSet<com_TerminoPago> com_TerminoPago { get; set; }
        public DbSet<com_tarjeta_orden_compra> com_tarjeta_orden_compra { get; set; }
        public DbSet<vwcom_cotizacion_compra_Edehsa> vwcom_cotizacion_compra_Edehsa { get; set; }
        public DbSet<vwcom_EstadoRecibido> vwcom_EstadoRecibido { get; set; }
        public DbSet<vwcom_ordencompra_local> vwcom_ordencompra_local { get; set; }
        public DbSet<vwcom_ordencompra_local_con_cant_devolver> vwcom_ordencompra_local_con_cant_devolver { get; set; }
        public DbSet<vwcom_ordencompra_local_det> vwcom_ordencompra_local_det { get; set; }
        public DbSet<vwcom_ordencompra_local_det_con_saldo_x_ing_a_inven> vwcom_ordencompra_local_det_con_saldo_x_ing_a_inven { get; set; }
        public DbSet<vwcom_ordencompra_local_det_con_saldo_x_ing_a_inven_con_saldo> vwcom_ordencompra_local_det_con_saldo_x_ing_a_inven_con_saldo { get; set; }
        public DbSet<vwcom_ordencompra_local_det_GE> vwcom_ordencompra_local_det_GE { get; set; }
        public DbSet<vwcom_ordencompra_local_det_x_cant_pedida_solic_compra> vwcom_ordencompra_local_det_x_cant_pedida_solic_compra { get; set; }
        public DbSet<vwcom_ordencompra_local_det_x_com_solicitud_compra_det> vwcom_ordencompra_local_det_x_com_solicitud_compra_det { get; set; }
        public DbSet<vwcom_ordencompra_local_det_x_MoviInven_SaldoItem> vwcom_ordencompra_local_det_x_MoviInven_SaldoItem { get; set; }
        public DbSet<vwcom_ordencompra_local_GE> vwcom_ordencompra_local_GE { get; set; }
        public DbSet<vwcom_ordencompra_local_x_com_solicitud_compra> vwcom_ordencompra_local_x_com_solicitud_compra { get; set; }
        public DbSet<vwcom_solicitud_compra> vwcom_solicitud_compra { get; set; }
        public DbSet<vwcom_solicitud_compra_det> vwcom_solicitud_compra_det { get; set; }
        public DbSet<vwcom_solicitud_compra_det_aprobacion> vwcom_solicitud_compra_det_aprobacion { get; set; }
        public DbSet<vwcom_solicitud_compra_det_x_Orden_Compra> vwcom_solicitud_compra_det_x_Orden_Compra { get; set; }
        public DbSet<vwcom_solicitud_compra_x_items_con_saldos> vwcom_solicitud_compra_x_items_con_saldos { get; set; }
        public DbSet<vwcom_solicitud_compra_X_Orden_Compra> vwcom_solicitud_compra_X_Orden_Compra { get; set; }
        public DbSet<vwcom_SolicitudCompra_Det_CantidadPedida_Compra> vwcom_SolicitudCompra_Det_CantidadPedida_Compra { get; set; }
        public DbSet<vwcom_SolicitudCompra_Det_SaldoPendiente> vwcom_SolicitudCompra_Det_SaldoPendiente { get; set; }
        public DbSet<vwcom_TerminoPago> vwcom_TerminoPago { get; set; }
    }
}
