//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesCuentasxPagar : DbContext
    {
        public EntitiesCuentasxPagar()
            : base("name=EntitiesCuentasxPagar")
        {
        }

        //poner esta funcion dentro de la clase entities no viene por defecto
        //10000 timeout 1 minutos
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cp_Aprobacion_Ing_Bod_x_OC> cp_Aprobacion_Ing_Bod_x_OC { get; set; }
        public DbSet<cp_Aprobacion_Ing_Bod_x_OC_det> cp_Aprobacion_Ing_Bod_x_OC_det { get; set; }
        public DbSet<cp_Aprobacion_Ing_Bod_x_OC_det_Eliminados> cp_Aprobacion_Ing_Bod_x_OC_det_Eliminados { get; set; }
        public DbSet<cp_Aprobacion_Ing_Bod_x_OC_Eliminados> cp_Aprobacion_Ing_Bod_x_OC_Eliminados { get; set; }
        public DbSet<cp_Aprobacion_Ing_Bod_x_OT> cp_Aprobacion_Ing_Bod_x_OT { get; set; }
        public DbSet<cp_Aprobacion_Orden_pago> cp_Aprobacion_Orden_pago { get; set; }
        public DbSet<cp_Aprobacion_Orden_pago_det> cp_Aprobacion_Orden_pago_det { get; set; }
        public DbSet<cp_Autorizacion_x_Doc_x_Pag> cp_Autorizacion_x_Doc_x_Pag { get; set; }
        public DbSet<cp_BaseImponible_x_CentroCosto_Edehsa> cp_BaseImponible_x_CentroCosto_Edehsa { get; set; }
        public DbSet<cp_catalogo> cp_catalogo { get; set; }
        public DbSet<cp_catalogo_tipo> cp_catalogo_tipo { get; set; }
        public DbSet<cp_codigo_SRI> cp_codigo_SRI { get; set; }
        public DbSet<cp_codigo_SRI_tipo> cp_codigo_SRI_tipo { get; set; }
        public DbSet<cp_codigo_SRI_x_CtaCble> cp_codigo_SRI_x_CtaCble { get; set; }
        public DbSet<cp_conciliacion> cp_conciliacion { get; set; }
        public DbSet<cp_conciliacion_Caja> cp_conciliacion_Caja { get; set; }
        public DbSet<cp_conciliacion_Caja_det> cp_conciliacion_Caja_det { get; set; }
        public DbSet<cp_conciliacion_Caja_det_Ing_Caja> cp_conciliacion_Caja_det_Ing_Caja { get; set; }
        public DbSet<cp_conciliacion_Caja_det_x_ValeCaja> cp_conciliacion_Caja_det_x_ValeCaja { get; set; }
        public DbSet<cp_conciliacion_det> cp_conciliacion_det { get; set; }
        public DbSet<cp_Conciliacion_Ing_Bodega_x_Orden_Giro> cp_Conciliacion_Ing_Bodega_x_Orden_Giro { get; set; }
        public DbSet<cp_cuotas_x_doc> cp_cuotas_x_doc { get; set; }
        public DbSet<cp_cuotas_x_doc_det> cp_cuotas_x_doc_det { get; set; }
        public DbSet<cp_estado> cp_estado { get; set; }
        public DbSet<cp_liquidacion_compra> cp_liquidacion_compra { get; set; }
        public DbSet<cp_liquidacion_compra_det> cp_liquidacion_compra_det { get; set; }
        public DbSet<cp_nota_DebCre> cp_nota_DebCre { get; set; }
        public DbSet<cp_nota_DebCre_Aprobacion_Ing_Bod_x_OC> cp_nota_DebCre_Aprobacion_Ing_Bod_x_OC { get; set; }
        public DbSet<cp_nota_DebCre_Aprobacion_Ing_Bod_x_OC_det> cp_nota_DebCre_Aprobacion_Ing_Bod_x_OC_det { get; set; }
        public DbSet<cp_nota_DebCre_Impuesto> cp_nota_DebCre_Impuesto { get; set; }
        public DbSet<cp_nota_DebCre_x_com_ordencompra_local> cp_nota_DebCre_x_com_ordencompra_local { get; set; }
        public DbSet<cp_orden_giro> cp_orden_giro { get; set; }
        public DbSet<cp_orden_giro_Impuesto> cp_orden_giro_Impuesto { get; set; }
        public DbSet<cp_orden_giro_pagos_sri> cp_orden_giro_pagos_sri { get; set; }
        public DbSet<cp_orden_giro_x_com_ordencompra_local> cp_orden_giro_x_com_ordencompra_local { get; set; }
        public DbSet<cp_orden_giro_x_com_ordencompra_local_det> cp_orden_giro_x_com_ordencompra_local_det { get; set; }
        public DbSet<cp_orden_giro_x_prd_OrdenTrabajo_Det> cp_orden_giro_x_prd_OrdenTrabajo_Det { get; set; }
        public DbSet<cp_orden_pago> cp_orden_pago { get; set; }
        public DbSet<cp_orden_pago_cancelaciones> cp_orden_pago_cancelaciones { get; set; }
        public DbSet<cp_orden_pago_con_Transferencia_data> cp_orden_pago_con_Transferencia_data { get; set; }
        public DbSet<cp_orden_pago_det> cp_orden_pago_det { get; set; }
        public DbSet<cp_orden_pago_estado_aprob> cp_orden_pago_estado_aprob { get; set; }
        public DbSet<cp_orden_pago_formapago> cp_orden_pago_formapago { get; set; }
        public DbSet<cp_orden_pago_tipo> cp_orden_pago_tipo { get; set; }
        public DbSet<cp_orden_pago_tipo_x_empresa> cp_orden_pago_tipo_x_empresa { get; set; }
        public DbSet<cp_orden_pago_x_empleado_x_nomina_x_periodo> cp_orden_pago_x_empleado_x_nomina_x_periodo { get; set; }
        public DbSet<cp_orden_pago_x_IdArchivo> cp_orden_pago_x_IdArchivo { get; set; }
        public DbSet<cp_pagos_sri> cp_pagos_sri { get; set; }
        public DbSet<cp_pais_sri> cp_pais_sri { get; set; }
        public DbSet<cp_parametros> cp_parametros { get; set; }
        public DbSet<cp_proveedor> cp_proveedor { get; set; }
        public DbSet<cp_proveedor_Autorizacion> cp_proveedor_Autorizacion { get; set; }
        public DbSet<cp_proveedor_Calificacion> cp_proveedor_Calificacion { get; set; }
        public DbSet<cp_proveedor_clase> cp_proveedor_clase { get; set; }
        public DbSet<cp_proveedor_codigo_SRI> cp_proveedor_codigo_SRI { get; set; }
        public DbSet<cp_proveedor_contactos> cp_proveedor_contactos { get; set; }
        public DbSet<cp_proveedor_datos_acreditacion> cp_proveedor_datos_acreditacion { get; set; }
        public DbSet<cp_proveedor_Filtro> cp_proveedor_Filtro { get; set; }
        public DbSet<cp_proveedor_x_IdCtaCble_CXC> cp_proveedor_x_IdCtaCble_CXC { get; set; }
        public DbSet<cp_proveedor_x_tb_ciiu> cp_proveedor_x_tb_ciiu { get; set; }
        public DbSet<cp_reembolso> cp_reembolso { get; set; }
        public DbSet<cp_retencion> cp_retencion { get; set; }
        public DbSet<cp_retencion_det> cp_retencion_det { get; set; }
        public DbSet<cp_retencion_x_ct_cbtecble> cp_retencion_x_ct_cbtecble { get; set; }
        public DbSet<cp_TerminoPago> cp_TerminoPago { get; set; }
        public DbSet<cp_TipoDocumento> cp_TipoDocumento { get; set; }
        public DbSet<cp_trans_a_generar_x_FormaPago_OP> cp_trans_a_generar_x_FormaPago_OP { get; set; }
        public DbSet<ct_Balance_x_General> ct_Balance_x_General { get; set; }
        public DbSet<cp_estado_cuenta_proveedor> cp_estado_cuenta_proveedor { get; set; }
        public DbSet<vwcp_Anticipos_para_Conciliar> vwcp_Anticipos_para_Conciliar { get; set; }
        public DbSet<vwcp_Anticipos_Proveedores> vwcp_Anticipos_Proveedores { get; set; }
        public DbSet<vwcp_Anticipos_x_NotaCred_Saldo> vwcp_Anticipos_x_NotaCred_Saldo { get; set; }
        public DbSet<vwcp_Aprobacion_Ing_Bod_x_OC> vwcp_Aprobacion_Ing_Bod_x_OC { get; set; }
        public DbSet<vwcp_Aprobacion_Ing_Bod_x_OC_det> vwcp_Aprobacion_Ing_Bod_x_OC_det { get; set; }
        public DbSet<vwcp_ba_Archivo_Transferencia_Det> vwcp_ba_Archivo_Transferencia_Det { get; set; }
        public DbSet<vwcp_base_retenciones> vwcp_base_retenciones { get; set; }
        public DbSet<vwcp_Cbte_x_pagar_OG> vwcp_Cbte_x_pagar_OG { get; set; }
        public DbSet<vwcp_cbtes_cxp_para_conciliar> vwcp_cbtes_cxp_para_conciliar { get; set; }
        public DbSet<vwcp_cbtes_cxp_para_conciliar_consulta> vwcp_cbtes_cxp_para_conciliar_consulta { get; set; }
        public DbSet<vwcp_codigo_SRI> vwcp_codigo_SRI { get; set; }
        public DbSet<vwcp_codigo_SRI_x_ctaCble> vwcp_codigo_SRI_x_ctaCble { get; set; }
        public DbSet<vwcp_comprobante_x_retencion> vwcp_comprobante_x_retencion { get; set; }
        public DbSet<vwcp_Conciliacion_Caja> vwcp_Conciliacion_Caja { get; set; }
        public DbSet<vwcp_Conciliacion_Caja_det> vwcp_Conciliacion_Caja_det { get; set; }
        public DbSet<vwcp_conciliacion_Caja_det_Ing_Caja> vwcp_conciliacion_Caja_det_Ing_Caja { get; set; }
        public DbSet<vwcp_conciliacion_Caja_det_Ing_Caja_total_aplicado> vwcp_conciliacion_Caja_det_Ing_Caja_total_aplicado { get; set; }
        public DbSet<vwcp_conciliacion_Caja_det_x_ValeCaja> vwcp_conciliacion_Caja_det_x_ValeCaja { get; set; }
        public DbSet<vwcp_conciliacion_det_x_cbte_pago> vwcp_conciliacion_det_x_cbte_pago { get; set; }
        public DbSet<vwcp_Conciliacion_Ing_Bodega_x_Orden_Giro> vwcp_Conciliacion_Ing_Bodega_x_Orden_Giro { get; set; }
        public DbSet<vwcp_Conciliacion_Poli> vwcp_Conciliacion_Poli { get; set; }
        public DbSet<vwcp_conciliacion_x_cbte_cble> vwcp_conciliacion_x_cbte_cble { get; set; }
        public DbSet<vwcp_conciliacion_x_orden_pago> vwcp_conciliacion_x_orden_pago { get; set; }
        public DbSet<vwcp_cp_retencion_x_empresa> vwcp_cp_retencion_x_empresa { get; set; }
        public DbSet<vwcp_liquidacionCompra_sri> vwcp_liquidacionCompra_sri { get; set; }
        public DbSet<vwcp_nota_DebCre> vwcp_nota_DebCre { get; set; }
        public DbSet<vwcp_nota_DebCre_ATS> vwcp_nota_DebCre_ATS { get; set; }
        public DbSet<vwcp_nota_DebCre_total_saldo> vwcp_nota_DebCre_total_saldo { get; set; }
        public DbSet<vwcp_Orden_Giro_Conciliado_x_Factura> vwcp_Orden_Giro_Conciliado_x_Factura { get; set; }
        public DbSet<vwcp_Orden_Giro_Conciliado_x_Ing_Bod_x_OC> vwcp_Orden_Giro_Conciliado_x_Ing_Bod_x_OC { get; set; }
        public DbSet<vwcp_orden_giro_cp_nota_DebCre_estcue> vwcp_orden_giro_cp_nota_DebCre_estcue { get; set; }
        public DbSet<vwcp_orden_giro_NotaDebito> vwcp_orden_giro_NotaDebito { get; set; }
        public DbSet<vwcp_Orden_Giro_Pendiente_Conciliar> vwcp_Orden_Giro_Pendiente_Conciliar { get; set; }
        public DbSet<vwcp_orden_giro_sin_retenciones> vwcp_orden_giro_sin_retenciones { get; set; }
        public DbSet<vwcp_orden_giro_SRI> vwcp_orden_giro_SRI { get; set; }
        public DbSet<vwcp_orden_giro_total_saldo> vwcp_orden_giro_total_saldo { get; set; }
        public DbSet<vwcp_orden_giro_x_com_ordencompra_local_det_consulta> vwcp_orden_giro_x_com_ordencompra_local_det_consulta { get; set; }
        public DbSet<vwcp_orden_giro_x_pagar> vwcp_orden_giro_x_pagar { get; set; }
        public DbSet<vwcp_orden_giro_x_Pagos_saldo> vwcp_orden_giro_x_Pagos_saldo { get; set; }
        public DbSet<vwcp_orden_giro_x_Pagos_saldo_SinIngresos> vwcp_orden_giro_x_Pagos_saldo_SinIngresos { get; set; }
        public DbSet<vwcp_orden_pago> vwcp_orden_pago { get; set; }
        public DbSet<vwcp_orden_pago_Anticipo_Saldo> vwcp_orden_pago_Anticipo_Saldo { get; set; }
        public DbSet<vwcp_orden_pago_cancelacion_Saldos> vwcp_orden_pago_cancelacion_Saldos { get; set; }
        public DbSet<vwcp_orden_pago_con_cancelacion> vwcp_orden_pago_con_cancelacion { get; set; }
        public DbSet<vwcp_orden_pago_con_cancelacion_lite> vwcp_orden_pago_con_cancelacion_lite { get; set; }
        public DbSet<vwcp_orden_pago_con_cancelacion_para_conciliacion> vwcp_orden_pago_con_cancelacion_para_conciliacion { get; set; }
        public DbSet<vwcp_orden_pago_con_cancelacion_x_CbteBan_Debi> vwcp_orden_pago_con_cancelacion_x_CbteBan_Debi { get; set; }
        public DbSet<vwcp_orden_pago_con_Transferencia> vwcp_orden_pago_con_Transferencia { get; set; }
        public DbSet<vwcp_orden_pago_det> vwcp_orden_pago_det { get; set; }
        public DbSet<vwcp_orden_pago_det_activa> vwcp_orden_pago_det_activa { get; set; }
        public DbSet<vwcp_orden_pago_det_con_cta_acreedora> vwcp_orden_pago_det_con_cta_acreedora { get; set; }
        public DbSet<vwcp_orden_pago_para_aprobacion> vwcp_orden_pago_para_aprobacion { get; set; }
        public DbSet<vwcp_orden_pago_tipo_x_empresa> vwcp_orden_pago_tipo_x_empresa { get; set; }
        public DbSet<vwcp_orden_pago_total> vwcp_orden_pago_total { get; set; }
        public DbSet<vwcp_orden_pago_Total_cancelacion> vwcp_orden_pago_Total_cancelacion { get; set; }
        public DbSet<vwcp_orden_pago_Total_Pagado> vwcp_orden_pago_Total_Pagado { get; set; }
        public DbSet<vwcp_orden_pago_Total_Pago> vwcp_orden_pago_Total_Pago { get; set; }
        public DbSet<vwcp_OrdenGiroRetencionReport> vwcp_OrdenGiroRetencionReport { get; set; }
        public DbSet<vwcp_proveedor_Calificacion> vwcp_proveedor_Calificacion { get; set; }
        public DbSet<vwcp_proveedor_vista_previa> vwcp_proveedor_vista_previa { get; set; }
        public DbSet<vwcp_ProveedorRuc> vwcp_ProveedorRuc { get; set; }
        public DbSet<vwcp_retencion> vwcp_retencion { get; set; }
        public DbSet<vwcp_Retencion_sri> vwcp_Retencion_sri { get; set; }
        public DbSet<vwCP_Retencion_Valor_total> vwCP_Retencion_Valor_total { get; set; }
        public DbSet<vwcp_Retencion_valor_total_x_cbte_cxp> vwcp_Retencion_valor_total_x_cbte_cxp { get; set; }
        public DbSet<vwcp_retencion_x_RET_FT> vwcp_retencion_x_RET_FT { get; set; }
        public DbSet<vwcp_retencion_x_RET_IVA> vwcp_retencion_x_RET_IVA { get; set; }
        public DbSet<vwcp_Retenciones_x_tipo_impresion> vwcp_Retenciones_x_tipo_impresion { get; set; }
        public DbSet<vwcp_Tipo_Impresion_Cheq> vwcp_Tipo_Impresion_Cheq { get; set; }
        public DbSet<vwcp_TipoServicioxProve> vwcp_TipoServicioxProve { get; set; }
    
        public virtual ObjectResult<string> spCXP_eliminar_factura_vale_conciliacion_caja(Nullable<int> p_IdEmpresa, Nullable<int> p_IdTipoCbte, Nullable<decimal> p_IdCbteCble, string p_TipoCbte_conci, Nullable<bool> p_Borrar_o_desvincular)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdTipoCbteParameter = p_IdTipoCbte.HasValue ?
                new ObjectParameter("p_IdTipoCbte", p_IdTipoCbte) :
                new ObjectParameter("p_IdTipoCbte", typeof(int));
    
            var p_IdCbteCbleParameter = p_IdCbteCble.HasValue ?
                new ObjectParameter("p_IdCbteCble", p_IdCbteCble) :
                new ObjectParameter("p_IdCbteCble", typeof(decimal));
    
            var p_TipoCbte_conciParameter = p_TipoCbte_conci != null ?
                new ObjectParameter("p_TipoCbte_conci", p_TipoCbte_conci) :
                new ObjectParameter("p_TipoCbte_conci", typeof(string));
    
            var p_Borrar_o_desvincularParameter = p_Borrar_o_desvincular.HasValue ?
                new ObjectParameter("p_Borrar_o_desvincular", p_Borrar_o_desvincular) :
                new ObjectParameter("p_Borrar_o_desvincular", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCXP_eliminar_factura_vale_conciliacion_caja", p_IdEmpresaParameter, p_IdTipoCbteParameter, p_IdCbteCbleParameter, p_TipoCbte_conciParameter, p_Borrar_o_desvincularParameter);
        }
    
        public virtual ObjectResult<spCXP_Anticipos_x_NotaCred_Saldo_Result> spCXP_Anticipos_x_NotaCred_Saldo(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdEntidad)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdEntidadParameter = p_IdEntidad.HasValue ?
                new ObjectParameter("p_IdEntidad", p_IdEntidad) :
                new ObjectParameter("p_IdEntidad", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Anticipos_x_NotaCred_Saldo_Result>("spCXP_Anticipos_x_NotaCred_Saldo", p_IdEmpresaParameter, p_IdEntidadParameter);
        }
    
        public virtual ObjectResult<spCXP_orden_pago_con_cancelacion_Result> spCXP_orden_pago_con_cancelacion(Nullable<int> p_IdEmpresa, string p_IdEstadoAprobacion, Nullable<decimal> p_IdPersona, Nullable<decimal> p_IdEntidad)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdEstadoAprobacionParameter = p_IdEstadoAprobacion != null ?
                new ObjectParameter("p_IdEstadoAprobacion", p_IdEstadoAprobacion) :
                new ObjectParameter("p_IdEstadoAprobacion", typeof(string));
    
            var p_IdPersonaParameter = p_IdPersona.HasValue ?
                new ObjectParameter("p_IdPersona", p_IdPersona) :
                new ObjectParameter("p_IdPersona", typeof(decimal));
    
            var p_IdEntidadParameter = p_IdEntidad.HasValue ?
                new ObjectParameter("p_IdEntidad", p_IdEntidad) :
                new ObjectParameter("p_IdEntidad", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_orden_pago_con_cancelacion_Result>("spCXP_orden_pago_con_cancelacion", p_IdEmpresaParameter, p_IdEstadoAprobacionParameter, p_IdPersonaParameter, p_IdEntidadParameter);
        }
    
        public virtual ObjectResult<spCXP_orden_pago_det_con_cta_acreedora_Result> spCXP_orden_pago_det_con_cta_acreedora(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdOrdenPago)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdOrdenPagoParameter = p_IdOrdenPago.HasValue ?
                new ObjectParameter("p_IdOrdenPago", p_IdOrdenPago) :
                new ObjectParameter("p_IdOrdenPago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_orden_pago_det_con_cta_acreedora_Result>("spCXP_orden_pago_det_con_cta_acreedora", p_IdEmpresaParameter, p_IdOrdenPagoParameter);
        }
    
        public virtual ObjectResult<spCXP_orden_pago_Result> spCXP_orden_pago(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_orden_pago_Result>("spCXP_orden_pago", p_IdEmpresaParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spcp_Get_Data_orden_pago_con_Transferencia_data_Result> spcp_Get_Data_orden_pago_con_Transferencia_data(Nullable<int> p_idempresa, Nullable<decimal> p_IdArchivo, Nullable<System.DateTime> p_fecha_ini, Nullable<System.DateTime> p_fecha_fin, string p_IdUsuario)
        {
            var p_idempresaParameter = p_idempresa.HasValue ?
                new ObjectParameter("p_idempresa", p_idempresa) :
                new ObjectParameter("p_idempresa", typeof(int));
    
            var p_IdArchivoParameter = p_IdArchivo.HasValue ?
                new ObjectParameter("p_IdArchivo", p_IdArchivo) :
                new ObjectParameter("p_IdArchivo", typeof(decimal));
    
            var p_fecha_iniParameter = p_fecha_ini.HasValue ?
                new ObjectParameter("p_fecha_ini", p_fecha_ini) :
                new ObjectParameter("p_fecha_ini", typeof(System.DateTime));
    
            var p_fecha_finParameter = p_fecha_fin.HasValue ?
                new ObjectParameter("p_fecha_fin", p_fecha_fin) :
                new ObjectParameter("p_fecha_fin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spcp_Get_Data_orden_pago_con_Transferencia_data_Result>("spcp_Get_Data_orden_pago_con_Transferencia_data", p_idempresaParameter, p_IdArchivoParameter, p_fecha_iniParameter, p_fecha_finParameter, p_IdUsuarioParameter);
        }
    }
}
