//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ComprobantesRecibidos
    {
        public int Id { get; set; }
        public string RucEmisor { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string TipoComprobante { get; set; }
        public string SerieComprobante { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string ClaveAcceso { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public string IdentificacionReceptor { get; set; }
        public Nullable<decimal> ValorSinImpuestos { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public string NumeroDocumentoModificado { get; set; }
        public string Estado { get; set; }
        public string Motivo { get; set; }
        public string XML { get; set; }
        public Nullable<int> IdEmpresa_Ogiro { get; set; }
        public Nullable<decimal> IdCbteCble_Ogiro { get; set; }
        public Nullable<int> IdTipoCbte_Ogiro { get; set; }
        public string NumeroAutorizacion { get; set; }
    }
}
