//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catastroGranContribuyente
    {
        public int id { get; set; }
        public string ruc { get; set; }
        public string razon_social { get; set; }
        public string oficio_atributo_gran_contribuyente { get; set; }
        public string provincia { get; set; }
        public string jurisdiccion { get; set; }
        public string descripcion_tipo { get; set; }
        public string descripcion_subtipo { get; set; }
    }
}
