//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_ordencompra_local_x_com_solicitud_compra
    {
        public int IdEmpresa_oc { get; set; }
        public int IdSucursal_oc { get; set; }
        public decimal IdOrdenCompra_oc { get; set; }
        public int IdEmpresa_sc { get; set; }
        public int IdSucursal_sc { get; set; }
        public decimal IdSolicitudCompra_sc { get; set; }
        public int Secuencia_sc { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public double Cantidad { get; set; }
        public string observacion { get; set; }
    }
}
