//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_orden_giro_cp_nota_DebCre_estcue
    {
        public int IdEmpresa { get; set; }
        public int IdTipoCbte { get; set; }
        public decimal IdCbteCble { get; set; }
        public decimal IdProveedor { get; set; }
        public string RazonSocial { get; set; }
        public string Observacion { get; set; }
        public string Documento { get; set; }
        public System.DateTime Fecha { get; set; }
        public double BaseImponible { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public string Estado { get; set; }
    }
}
