//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp_NOTA
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Nota { get; set; }
        public int IdTipoCbte_Nota { get; set; }
        public System.DateTime cn_fecha { get; set; }
        public string cn_observacion { get; set; }
        public string referncia { get; set; }
        public string tc_TipoCbte { get; set; }
        public decimal Valor_Cbte { get; set; }
        public double Valor_Cancelado_cbte { get; set; }
        public double Valor_saldo_cbte { get; set; }
        public string Tipo { get; set; }
        public string IdCtaCble { get; set; }
        public string IdCtaAnticipo { get; set; }
        public string Beneficiario { get; set; }
        public decimal IdProveedor { get; set; }
    }
}
