//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_GuiaRemision_Lite
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public decimal IdGuiaRemision { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public string nom_bodega { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaTrasladoIni { get; set; }
        public System.DateTime FechaTrasladoFin { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public string NumDocumento { get; set; }
        public string IdTipo_Persona { get; set; }
        public decimal IdEntidad { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string NomProyecto { get; set; }
        public string IdCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Observacion { get; set; }
        public int IdMotivo { get; set; }
        public string Motivo { get; set; }
        public string IdEstado_cierre { get; set; }
        public string Estado { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string NumAutorizacion { get; set; }
        public int IdTransportista { get; set; }
        public string CedulaTransportista { get; set; }
        public string NombreTransportista { get; set; }
        public string Placa { get; set; }
        public string Ruta { get; set; }
        public string Correo { get; set; }
    }
}
