//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesCXP_General : DbContext
    {
        public EntitiesCXP_General()
            : base("name=EntitiesCXP_General")
        {
        }

        //poner esta funcion dentro de la clase entities no viene por defecto
        //10000 timeout 1 minutos
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCXP_Rpt004> vwCXP_Rpt004 { get; set; }
        public DbSet<vwCXP_Rpt005> vwCXP_Rpt005 { get; set; }
        public DbSet<vwCXP_Rpt006> vwCXP_Rpt006 { get; set; }
        public DbSet<vwCXP_Rpt007> vwCXP_Rpt007 { get; set; }
        public DbSet<vwCXP_Rpt011> vwCXP_Rpt011 { get; set; }
        public DbSet<vwCXP_Rpt015> vwCXP_Rpt015 { get; set; }
        public DbSet<vwCXP_Rpt018> vwCXP_Rpt018 { get; set; }
        public DbSet<vwCXP_Rpt019> vwCXP_Rpt019 { get; set; }
        public DbSet<vwCXP_Rpt021> vwCXP_Rpt021 { get; set; }
        public DbSet<vwCXP_Rpt022> vwCXP_Rpt022 { get; set; }
        public DbSet<vwCXP_Rpt023> vwCXP_Rpt023 { get; set; }
        public DbSet<vwCXP_Rpt024> vwCXP_Rpt024 { get; set; }
        public DbSet<vwCXP_Rpt026> vwCXP_Rpt026 { get; set; }
        public DbSet<vwCXP_Rpt027> vwCXP_Rpt027 { get; set; }
        public DbSet<vwCXP_Rpt028> vwCXP_Rpt028 { get; set; }
        public DbSet<vwCXP_Rpt030> vwCXP_Rpt030 { get; set; }
        public DbSet<vwCXP_Rpt031> vwCXP_Rpt031 { get; set; }
        public DbSet<vwCXP_Rpt032> vwCXP_Rpt032 { get; set; }
        public DbSet<vwCXP_Rpt033> vwCXP_Rpt033 { get; set; }
        public DbSet<vwCXP_Rpt034> vwCXP_Rpt034 { get; set; }
        public DbSet<vwCXP_Rpt036> vwCXP_Rpt036 { get; set; }
        public DbSet<vwCXP_Rpt003> vwCXP_Rpt003 { get; set; }
        public DbSet<vwCXP_Rpt039> vwCXP_Rpt039 { get; set; }
        public DbSet<vwCXP_Rpt002> vwCXP_Rpt002 { get; set; }
        public DbSet<vwCXP_Rpt010> vwCXP_Rpt010 { get; set; }
        public DbSet<vwCXP_Rpt012> vwCXP_Rpt012 { get; set; }
        public DbSet<vwCXP_Rpt025> vwCXP_Rpt025 { get; set; }
        public DbSet<vwCXP_Rpt040> vwCXP_Rpt040 { get; set; }
        public DbSet<vwCXP_Rpt001> vwCXP_Rpt001 { get; set; }
        public DbSet<vwCXP_Rpt016> vwCXP_Rpt016 { get; set; }
        public DbSet<vwCXP_Rpt029> vwCXP_Rpt029 { get; set; }
    
        public virtual ObjectResult<spCXP_Rpt008_Result> spCXP_Rpt008(Nullable<int> p_IdEmpresa, Nullable<int> p_IdClase_ini, Nullable<int> p_IdClase_fin, Nullable<decimal> p_IdProveedor_ini, Nullable<decimal> p_IdProveedor_fin, Nullable<System.DateTime> p_Fecha_corte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdClase_iniParameter = p_IdClase_ini.HasValue ?
                new ObjectParameter("p_IdClase_ini", p_IdClase_ini) :
                new ObjectParameter("p_IdClase_ini", typeof(int));
    
            var p_IdClase_finParameter = p_IdClase_fin.HasValue ?
                new ObjectParameter("p_IdClase_fin", p_IdClase_fin) :
                new ObjectParameter("p_IdClase_fin", typeof(int));
    
            var p_IdProveedor_iniParameter = p_IdProveedor_ini.HasValue ?
                new ObjectParameter("p_IdProveedor_ini", p_IdProveedor_ini) :
                new ObjectParameter("p_IdProveedor_ini", typeof(decimal));
    
            var p_IdProveedor_finParameter = p_IdProveedor_fin.HasValue ?
                new ObjectParameter("p_IdProveedor_fin", p_IdProveedor_fin) :
                new ObjectParameter("p_IdProveedor_fin", typeof(decimal));
    
            var p_Fecha_corteParameter = p_Fecha_corte.HasValue ?
                new ObjectParameter("p_Fecha_corte", p_Fecha_corte) :
                new ObjectParameter("p_Fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt008_Result>("spCXP_Rpt008", p_IdEmpresaParameter, p_IdClase_iniParameter, p_IdClase_finParameter, p_IdProveedor_iniParameter, p_IdProveedor_finParameter, p_Fecha_corteParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt013_Result> spCXP_Rpt013(Nullable<int> p_idempresa, Nullable<System.DateTime> p_fecha, Nullable<decimal> p_idProveedorIni, Nullable<decimal> p_idProveedorFIn)
        {
            var p_idempresaParameter = p_idempresa.HasValue ?
                new ObjectParameter("p_idempresa", p_idempresa) :
                new ObjectParameter("p_idempresa", typeof(int));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_idProveedorIniParameter = p_idProveedorIni.HasValue ?
                new ObjectParameter("p_idProveedorIni", p_idProveedorIni) :
                new ObjectParameter("p_idProveedorIni", typeof(decimal));
    
            var p_idProveedorFInParameter = p_idProveedorFIn.HasValue ?
                new ObjectParameter("p_idProveedorFIn", p_idProveedorFIn) :
                new ObjectParameter("p_idProveedorFIn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt013_Result>("spCXP_Rpt013", p_idempresaParameter, p_fechaParameter, p_idProveedorIniParameter, p_idProveedorFInParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt014_Result> spCXP_Rpt014(Nullable<int> p_idempresa, Nullable<System.DateTime> p_fecha, Nullable<decimal> p_idProveedorIni, Nullable<decimal> p_idProveedorFIn)
        {
            var p_idempresaParameter = p_idempresa.HasValue ?
                new ObjectParameter("p_idempresa", p_idempresa) :
                new ObjectParameter("p_idempresa", typeof(int));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_idProveedorIniParameter = p_idProveedorIni.HasValue ?
                new ObjectParameter("p_idProveedorIni", p_idProveedorIni) :
                new ObjectParameter("p_idProveedorIni", typeof(decimal));
    
            var p_idProveedorFInParameter = p_idProveedorFIn.HasValue ?
                new ObjectParameter("p_idProveedorFIn", p_idProveedorFIn) :
                new ObjectParameter("p_idProveedorFIn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt014_Result>("spCXP_Rpt014", p_idempresaParameter, p_fechaParameter, p_idProveedorIniParameter, p_idProveedorFInParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt035_Result> spCXP_Rpt035(Nullable<int> p_idempresa, Nullable<System.DateTime> p_fecha, Nullable<decimal> p_idProveedorIni, Nullable<decimal> p_idProveedorFIn)
        {
            var p_idempresaParameter = p_idempresa.HasValue ?
                new ObjectParameter("p_idempresa", p_idempresa) :
                new ObjectParameter("p_idempresa", typeof(int));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_idProveedorIniParameter = p_idProveedorIni.HasValue ?
                new ObjectParameter("p_idProveedorIni", p_idProveedorIni) :
                new ObjectParameter("p_idProveedorIni", typeof(decimal));
    
            var p_idProveedorFInParameter = p_idProveedorFIn.HasValue ?
                new ObjectParameter("p_idProveedorFIn", p_idProveedorFIn) :
                new ObjectParameter("p_idProveedorFIn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt035_Result>("spCXP_Rpt035", p_idempresaParameter, p_fechaParameter, p_idProveedorIniParameter, p_idProveedorFInParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt038_Result> spCXP_Rpt038(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fechaIni, Nullable<System.DateTime> p_fechaFin, Nullable<int> p_IdProveedorIni, Nullable<int> p_IdProveedorFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fechaIniParameter = p_fechaIni.HasValue ?
                new ObjectParameter("p_fechaIni", p_fechaIni) :
                new ObjectParameter("p_fechaIni", typeof(System.DateTime));
    
            var p_fechaFinParameter = p_fechaFin.HasValue ?
                new ObjectParameter("p_fechaFin", p_fechaFin) :
                new ObjectParameter("p_fechaFin", typeof(System.DateTime));
    
            var p_IdProveedorIniParameter = p_IdProveedorIni.HasValue ?
                new ObjectParameter("p_IdProveedorIni", p_IdProveedorIni) :
                new ObjectParameter("p_IdProveedorIni", typeof(int));
    
            var p_IdProveedorFinParameter = p_IdProveedorFin.HasValue ?
                new ObjectParameter("p_IdProveedorFin", p_IdProveedorFin) :
                new ObjectParameter("p_IdProveedorFin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt038_Result>("spCXP_Rpt038", p_IdEmpresaParameter, p_fechaIniParameter, p_fechaFinParameter, p_IdProveedorIniParameter, p_IdProveedorFinParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt037_Result> spCXP_Rpt037(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fechaIni, Nullable<System.DateTime> p_fechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fechaIniParameter = p_fechaIni.HasValue ?
                new ObjectParameter("p_fechaIni", p_fechaIni) :
                new ObjectParameter("p_fechaIni", typeof(System.DateTime));
    
            var p_fechaFinParameter = p_fechaFin.HasValue ?
                new ObjectParameter("p_fechaFin", p_fechaFin) :
                new ObjectParameter("p_fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt037_Result>("spCXP_Rpt037", p_IdEmpresaParameter, p_fechaIniParameter, p_fechaFinParameter);
        }
    
        public virtual ObjectResult<spXCXP_Rpt036_Result> spXCXP_Rpt036(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fechaIni, Nullable<System.DateTime> p_fechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fechaIniParameter = p_fechaIni.HasValue ?
                new ObjectParameter("p_fechaIni", p_fechaIni) :
                new ObjectParameter("p_fechaIni", typeof(System.DateTime));
    
            var p_fechaFinParameter = p_fechaFin.HasValue ?
                new ObjectParameter("p_fechaFin", p_fechaFin) :
                new ObjectParameter("p_fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spXCXP_Rpt036_Result>("spXCXP_Rpt036", p_IdEmpresaParameter, p_fechaIniParameter, p_fechaFinParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt041_Result> spCXP_Rpt041(Nullable<int> p_IdEmpresa, string p_IdTipo_Persona, Nullable<int> p_IdEntidad, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdTipo_PersonaParameter = p_IdTipo_Persona != null ?
                new ObjectParameter("p_IdTipo_Persona", p_IdTipo_Persona) :
                new ObjectParameter("p_IdTipo_Persona", typeof(string));
    
            var p_IdEntidadParameter = p_IdEntidad.HasValue ?
                new ObjectParameter("p_IdEntidad", p_IdEntidad) :
                new ObjectParameter("p_IdEntidad", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt041_Result>("spCXP_Rpt041", p_IdEmpresaParameter, p_IdTipo_PersonaParameter, p_IdEntidadParameter, p_FechaIniParameter, p_FechaFinParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt017_Result> spCXP_Rpt017(Nullable<int> p_idempresa, Nullable<System.DateTime> p_fecha, Nullable<decimal> p_idProveedorIni, Nullable<decimal> p_idProveedorFIn)
        {
            var p_idempresaParameter = p_idempresa.HasValue ?
                new ObjectParameter("p_idempresa", p_idempresa) :
                new ObjectParameter("p_idempresa", typeof(int));
    
            var p_fechaParameter = p_fecha.HasValue ?
                new ObjectParameter("p_fecha", p_fecha) :
                new ObjectParameter("p_fecha", typeof(System.DateTime));
    
            var p_idProveedorIniParameter = p_idProveedorIni.HasValue ?
                new ObjectParameter("p_idProveedorIni", p_idProveedorIni) :
                new ObjectParameter("p_idProveedorIni", typeof(decimal));
    
            var p_idProveedorFInParameter = p_idProveedorFIn.HasValue ?
                new ObjectParameter("p_idProveedorFIn", p_idProveedorFIn) :
                new ObjectParameter("p_idProveedorFIn", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt017_Result>("spCXP_Rpt017", p_idempresaParameter, p_fechaParameter, p_idProveedorIniParameter, p_idProveedorFInParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt042_Result> spCXP_Rpt042(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt042_Result>("spCXP_Rpt042", p_IdEmpresaParameter, p_FechaIniParameter, p_FechaFinParameter);
        }
    
        public virtual ObjectResult<spCXP_Rpt043_Result> spCXP_Rpt043(Nullable<int> p_IdEmpresa, Nullable<decimal> p_IdProveedorIni, Nullable<decimal> p_IdProveedorFin, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdProveedorIniParameter = p_IdProveedorIni.HasValue ?
                new ObjectParameter("p_IdProveedorIni", p_IdProveedorIni) :
                new ObjectParameter("p_IdProveedorIni", typeof(decimal));
    
            var p_IdProveedorFinParameter = p_IdProveedorFin.HasValue ?
                new ObjectParameter("p_IdProveedorFin", p_IdProveedorFin) :
                new ObjectParameter("p_IdProveedorFin", typeof(decimal));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXP_Rpt043_Result>("spCXP_Rpt043", p_IdEmpresaParameter, p_IdProveedorIniParameter, p_IdProveedorFinParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdUsuarioParameter);
        }
    }
}
