//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_Inventario_General : DbContext
    {
        public Entities_Inventario_General()
            : base("name=Entities_Inventario_General")
        {
        }

        //poner esta funcion dentro de la clase entities no viene por defecto
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwINV_Rpt004> vwINV_Rpt004 { get; set; }
        public DbSet<vwINV_Rpt006> vwINV_Rpt006 { get; set; }
        public DbSet<vwINV_Rpt005> vwINV_Rpt005 { get; set; }
        public DbSet<vwINV_Rpt016> vwINV_Rpt016 { get; set; }
        public DbSet<vwINV_Rpt010> vwINV_Rpt010 { get; set; }
        public DbSet<vwINV_Rpt011> vwINV_Rpt011 { get; set; }
        public DbSet<vwINV_Rpt024> vwINV_Rpt024 { get; set; }
        public DbSet<vwINV_Rpt019> vwINV_Rpt019 { get; set; }
        public DbSet<vwINV_Rpt012> vwINV_Rpt012 { get; set; }
        public DbSet<vwINV_Rpt025> vwINV_Rpt025 { get; set; }
        public DbSet<vwINV_Rpt028> vwINV_Rpt028 { get; set; }
        public DbSet<vwINV_Rpt017> vwINV_Rpt017 { get; set; }
        public DbSet<vwINV_Rpt023> vwINV_Rpt023 { get; set; }
        public DbSet<vwINV_Rpt031> vwINV_Rpt031 { get; set; }
        public DbSet<vwINV_Rpt037> vwINV_Rpt037 { get; set; }
        public DbSet<vwINV_Rpt038> vwINV_Rpt038 { get; set; }
        public DbSet<vwINV_Rpt039> vwINV_Rpt039 { get; set; }
        public DbSet<vwINV_Rpt041> vwINV_Rpt041 { get; set; }
        public DbSet<vwINV_Rpt003> vwINV_Rpt003 { get; set; }
        public DbSet<vwINV_Rpt002> vwINV_Rpt002 { get; set; }
        public DbSet<vwINV_Rpt001> vwINV_Rpt001 { get; set; }
        public DbSet<vwINV_Rpt007> vwINV_Rpt007 { get; set; }
        public DbSet<vwINV_Rpt022> vwINV_Rpt022 { get; set; }
        public DbSet<vwINV_Rpt030> vwINV_Rpt030 { get; set; }
        public DbSet<vwINV_Rpt013> vwINV_Rpt013 { get; set; }
        public DbSet<vwINV_Rpt015> vwINV_Rpt015 { get; set; }
    
        public virtual ObjectResult<spINV_Rpt011_Result> spINV_Rpt011(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursalIni, Nullable<int> p_IdSucursalFin, Nullable<int> p_IdBodegaIni, Nullable<int> p_IdBodegaFin, Nullable<decimal> p_IdProductoIni, Nullable<decimal> p_IdProductoFin, Nullable<System.DateTime> p_FechaCorteIni)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(int));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(int));
    
            var p_IdBodegaIniParameter = p_IdBodegaIni.HasValue ?
                new ObjectParameter("p_IdBodegaIni", p_IdBodegaIni) :
                new ObjectParameter("p_IdBodegaIni", typeof(int));
    
            var p_IdBodegaFinParameter = p_IdBodegaFin.HasValue ?
                new ObjectParameter("p_IdBodegaFin", p_IdBodegaFin) :
                new ObjectParameter("p_IdBodegaFin", typeof(int));
    
            var p_IdProductoIniParameter = p_IdProductoIni.HasValue ?
                new ObjectParameter("p_IdProductoIni", p_IdProductoIni) :
                new ObjectParameter("p_IdProductoIni", typeof(decimal));
    
            var p_IdProductoFinParameter = p_IdProductoFin.HasValue ?
                new ObjectParameter("p_IdProductoFin", p_IdProductoFin) :
                new ObjectParameter("p_IdProductoFin", typeof(decimal));
    
            var p_FechaCorteIniParameter = p_FechaCorteIni.HasValue ?
                new ObjectParameter("p_FechaCorteIni", p_FechaCorteIni) :
                new ObjectParameter("p_FechaCorteIni", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt011_Result>("spINV_Rpt011", p_IdEmpresaParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_IdBodegaIniParameter, p_IdBodegaFinParameter, p_IdProductoIniParameter, p_IdProductoFinParameter, p_FechaCorteIniParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt018_Result> spINV_Rpt018(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursalIni, Nullable<int> p_IdSucursalFin, Nullable<int> p_IdBodegaIni, Nullable<int> p_IdBodegaFin, Nullable<int> p_IdProductoIni, Nullable<int> p_IdProductoFin, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_dias_stock, Nullable<bool> p_Mostrar_reg_en_cero)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(int));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(int));
    
            var p_IdBodegaIniParameter = p_IdBodegaIni.HasValue ?
                new ObjectParameter("p_IdBodegaIni", p_IdBodegaIni) :
                new ObjectParameter("p_IdBodegaIni", typeof(int));
    
            var p_IdBodegaFinParameter = p_IdBodegaFin.HasValue ?
                new ObjectParameter("p_IdBodegaFin", p_IdBodegaFin) :
                new ObjectParameter("p_IdBodegaFin", typeof(int));
    
            var p_IdProductoIniParameter = p_IdProductoIni.HasValue ?
                new ObjectParameter("p_IdProductoIni", p_IdProductoIni) :
                new ObjectParameter("p_IdProductoIni", typeof(int));
    
            var p_IdProductoFinParameter = p_IdProductoFin.HasValue ?
                new ObjectParameter("p_IdProductoFin", p_IdProductoFin) :
                new ObjectParameter("p_IdProductoFin", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_dias_stockParameter = p_dias_stock.HasValue ?
                new ObjectParameter("p_dias_stock", p_dias_stock) :
                new ObjectParameter("p_dias_stock", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt018_Result>("spINV_Rpt018", p_IdEmpresaParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_IdBodegaIniParameter, p_IdBodegaFinParameter, p_IdProductoIniParameter, p_IdProductoFinParameter, p_FechaIniParameter, p_FechaFinParameter, p_dias_stockParameter, p_Mostrar_reg_en_ceroParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt021_Result> spINV_Rpt021(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursalIni, Nullable<int> p_IdSucursalFin, Nullable<int> p_IdBodegaIni, Nullable<int> p_IdBodegaFin, Nullable<int> p_IdProductoIni, Nullable<int> p_IdProductoFin, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_dias_stock, Nullable<bool> p_Mostrar_reg_en_cero)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(int));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(int));
    
            var p_IdBodegaIniParameter = p_IdBodegaIni.HasValue ?
                new ObjectParameter("p_IdBodegaIni", p_IdBodegaIni) :
                new ObjectParameter("p_IdBodegaIni", typeof(int));
    
            var p_IdBodegaFinParameter = p_IdBodegaFin.HasValue ?
                new ObjectParameter("p_IdBodegaFin", p_IdBodegaFin) :
                new ObjectParameter("p_IdBodegaFin", typeof(int));
    
            var p_IdProductoIniParameter = p_IdProductoIni.HasValue ?
                new ObjectParameter("p_IdProductoIni", p_IdProductoIni) :
                new ObjectParameter("p_IdProductoIni", typeof(int));
    
            var p_IdProductoFinParameter = p_IdProductoFin.HasValue ?
                new ObjectParameter("p_IdProductoFin", p_IdProductoFin) :
                new ObjectParameter("p_IdProductoFin", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_dias_stockParameter = p_dias_stock.HasValue ?
                new ObjectParameter("p_dias_stock", p_dias_stock) :
                new ObjectParameter("p_dias_stock", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt021_Result>("spINV_Rpt021", p_IdEmpresaParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_IdBodegaIniParameter, p_IdBodegaFinParameter, p_IdProductoIniParameter, p_IdProductoFinParameter, p_FechaIniParameter, p_FechaFinParameter, p_dias_stockParameter, p_Mostrar_reg_en_ceroParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt026_Result> spINV_Rpt026(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal_ini, Nullable<int> p_IdSucursal_fin, Nullable<int> p_IdBodega_ini, Nullable<int> p_IdBodega_fin, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursal_iniParameter = p_IdSucursal_ini.HasValue ?
                new ObjectParameter("p_IdSucursal_ini", p_IdSucursal_ini) :
                new ObjectParameter("p_IdSucursal_ini", typeof(int));
    
            var p_IdSucursal_finParameter = p_IdSucursal_fin.HasValue ?
                new ObjectParameter("p_IdSucursal_fin", p_IdSucursal_fin) :
                new ObjectParameter("p_IdSucursal_fin", typeof(int));
    
            var p_IdBodega_iniParameter = p_IdBodega_ini.HasValue ?
                new ObjectParameter("p_IdBodega_ini", p_IdBodega_ini) :
                new ObjectParameter("p_IdBodega_ini", typeof(int));
    
            var p_IdBodega_finParameter = p_IdBodega_fin.HasValue ?
                new ObjectParameter("p_IdBodega_fin", p_IdBodega_fin) :
                new ObjectParameter("p_IdBodega_fin", typeof(int));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt026_Result>("spINV_Rpt026", p_IdEmpresaParameter, p_IdSucursal_iniParameter, p_IdSucursal_finParameter, p_IdBodega_iniParameter, p_IdBodega_finParameter, p_Fecha_iniParameter, p_Fecha_finParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt027_Result> spINV_Rpt027(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal_ini, Nullable<int> p_IdSucursal_fin, Nullable<int> p_IdBodega_ini, Nullable<int> p_IdBodega_fin, Nullable<decimal> p_IdProducto_ini, Nullable<decimal> p_IdProducto_fin, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin, string p_IdUsuario, Nullable<bool> p_No_Mostrar_valores_en_0, Nullable<bool> p_Mostrar_detallado)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursal_iniParameter = p_IdSucursal_ini.HasValue ?
                new ObjectParameter("p_IdSucursal_ini", p_IdSucursal_ini) :
                new ObjectParameter("p_IdSucursal_ini", typeof(int));
    
            var p_IdSucursal_finParameter = p_IdSucursal_fin.HasValue ?
                new ObjectParameter("p_IdSucursal_fin", p_IdSucursal_fin) :
                new ObjectParameter("p_IdSucursal_fin", typeof(int));
    
            var p_IdBodega_iniParameter = p_IdBodega_ini.HasValue ?
                new ObjectParameter("p_IdBodega_ini", p_IdBodega_ini) :
                new ObjectParameter("p_IdBodega_ini", typeof(int));
    
            var p_IdBodega_finParameter = p_IdBodega_fin.HasValue ?
                new ObjectParameter("p_IdBodega_fin", p_IdBodega_fin) :
                new ObjectParameter("p_IdBodega_fin", typeof(int));
    
            var p_IdProducto_iniParameter = p_IdProducto_ini.HasValue ?
                new ObjectParameter("p_IdProducto_ini", p_IdProducto_ini) :
                new ObjectParameter("p_IdProducto_ini", typeof(decimal));
    
            var p_IdProducto_finParameter = p_IdProducto_fin.HasValue ?
                new ObjectParameter("p_IdProducto_fin", p_IdProducto_fin) :
                new ObjectParameter("p_IdProducto_fin", typeof(decimal));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            var p_No_Mostrar_valores_en_0Parameter = p_No_Mostrar_valores_en_0.HasValue ?
                new ObjectParameter("p_No_Mostrar_valores_en_0", p_No_Mostrar_valores_en_0) :
                new ObjectParameter("p_No_Mostrar_valores_en_0", typeof(bool));
    
            var p_Mostrar_detalladoParameter = p_Mostrar_detallado.HasValue ?
                new ObjectParameter("p_Mostrar_detallado", p_Mostrar_detallado) :
                new ObjectParameter("p_Mostrar_detallado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt027_Result>("spINV_Rpt027", p_IdEmpresaParameter, p_IdSucursal_iniParameter, p_IdSucursal_finParameter, p_IdBodega_iniParameter, p_IdBodega_finParameter, p_IdProducto_iniParameter, p_IdProducto_finParameter, p_Fecha_iniParameter, p_Fecha_finParameter, p_IdUsuarioParameter, p_No_Mostrar_valores_en_0Parameter, p_Mostrar_detalladoParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt029_Result> spINV_Rpt029(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal_ini, Nullable<int> p_IdSucursal_fin, Nullable<int> p_IdBodega_ini, Nullable<int> p_IdBodega_fin, Nullable<System.DateTime> p_fecha_corte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursal_iniParameter = p_IdSucursal_ini.HasValue ?
                new ObjectParameter("p_IdSucursal_ini", p_IdSucursal_ini) :
                new ObjectParameter("p_IdSucursal_ini", typeof(int));
    
            var p_IdSucursal_finParameter = p_IdSucursal_fin.HasValue ?
                new ObjectParameter("p_IdSucursal_fin", p_IdSucursal_fin) :
                new ObjectParameter("p_IdSucursal_fin", typeof(int));
    
            var p_IdBodega_iniParameter = p_IdBodega_ini.HasValue ?
                new ObjectParameter("p_IdBodega_ini", p_IdBodega_ini) :
                new ObjectParameter("p_IdBodega_ini", typeof(int));
    
            var p_IdBodega_finParameter = p_IdBodega_fin.HasValue ?
                new ObjectParameter("p_IdBodega_fin", p_IdBodega_fin) :
                new ObjectParameter("p_IdBodega_fin", typeof(int));
    
            var p_fecha_corteParameter = p_fecha_corte.HasValue ?
                new ObjectParameter("p_fecha_corte", p_fecha_corte) :
                new ObjectParameter("p_fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt029_Result>("spINV_Rpt029", p_IdEmpresaParameter, p_IdSucursal_iniParameter, p_IdSucursal_finParameter, p_IdBodega_iniParameter, p_IdBodega_finParameter, p_fecha_corteParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt009_Result> spINV_Rpt009(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal_ini, Nullable<int> p_IdSucursal_fin, Nullable<int> p_IdBodega_ini, Nullable<int> p_IdBodega_fin, Nullable<decimal> p_IdProducto_ini, Nullable<decimal> p_IdProducto_fin, Nullable<System.DateTime> p_fecha_corte)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursal_iniParameter = p_IdSucursal_ini.HasValue ?
                new ObjectParameter("p_IdSucursal_ini", p_IdSucursal_ini) :
                new ObjectParameter("p_IdSucursal_ini", typeof(int));
    
            var p_IdSucursal_finParameter = p_IdSucursal_fin.HasValue ?
                new ObjectParameter("p_IdSucursal_fin", p_IdSucursal_fin) :
                new ObjectParameter("p_IdSucursal_fin", typeof(int));
    
            var p_IdBodega_iniParameter = p_IdBodega_ini.HasValue ?
                new ObjectParameter("p_IdBodega_ini", p_IdBodega_ini) :
                new ObjectParameter("p_IdBodega_ini", typeof(int));
    
            var p_IdBodega_finParameter = p_IdBodega_fin.HasValue ?
                new ObjectParameter("p_IdBodega_fin", p_IdBodega_fin) :
                new ObjectParameter("p_IdBodega_fin", typeof(int));
    
            var p_IdProducto_iniParameter = p_IdProducto_ini.HasValue ?
                new ObjectParameter("p_IdProducto_ini", p_IdProducto_ini) :
                new ObjectParameter("p_IdProducto_ini", typeof(decimal));
    
            var p_IdProducto_finParameter = p_IdProducto_fin.HasValue ?
                new ObjectParameter("p_IdProducto_fin", p_IdProducto_fin) :
                new ObjectParameter("p_IdProducto_fin", typeof(decimal));
    
            var p_fecha_corteParameter = p_fecha_corte.HasValue ?
                new ObjectParameter("p_fecha_corte", p_fecha_corte) :
                new ObjectParameter("p_fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt009_Result>("spINV_Rpt009", p_IdEmpresaParameter, p_IdSucursal_iniParameter, p_IdSucursal_finParameter, p_IdBodega_iniParameter, p_IdBodega_finParameter, p_IdProducto_iniParameter, p_IdProducto_finParameter, p_fecha_corteParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt009_Edehsa_Result> spINV_Rpt009_Edehsa(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal, Nullable<decimal> p_IdProducto_ini, Nullable<decimal> p_IdProducto_fin, Nullable<System.DateTime> p_fecha_corte, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalParameter = p_IdSucursal.HasValue ?
                new ObjectParameter("p_IdSucursal", p_IdSucursal) :
                new ObjectParameter("p_IdSucursal", typeof(int));
    
            var p_IdProducto_iniParameter = p_IdProducto_ini.HasValue ?
                new ObjectParameter("p_IdProducto_ini", p_IdProducto_ini) :
                new ObjectParameter("p_IdProducto_ini", typeof(decimal));
    
            var p_IdProducto_finParameter = p_IdProducto_fin.HasValue ?
                new ObjectParameter("p_IdProducto_fin", p_IdProducto_fin) :
                new ObjectParameter("p_IdProducto_fin", typeof(decimal));
    
            var p_fecha_corteParameter = p_fecha_corte.HasValue ?
                new ObjectParameter("p_fecha_corte", p_fecha_corte) :
                new ObjectParameter("p_fecha_corte", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt009_Edehsa_Result>("spINV_Rpt009_Edehsa", p_IdEmpresaParameter, p_IdSucursalParameter, p_IdProducto_iniParameter, p_IdProducto_finParameter, p_fecha_corteParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt010_Result> spINV_Rpt010(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursal_ini, Nullable<int> p_IdSucursal_fin, Nullable<int> p_IdBodega_ini, Nullable<int> p_IdBodega_fin, Nullable<decimal> p_IdProducto_ini, Nullable<decimal> p_IdProducto_fin, Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin, string p_IdUsuario, Nullable<bool> p_No_Mostrar_valores_en_0, Nullable<bool> p_Mostrar_detallado)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursal_iniParameter = p_IdSucursal_ini.HasValue ?
                new ObjectParameter("p_IdSucursal_ini", p_IdSucursal_ini) :
                new ObjectParameter("p_IdSucursal_ini", typeof(int));
    
            var p_IdSucursal_finParameter = p_IdSucursal_fin.HasValue ?
                new ObjectParameter("p_IdSucursal_fin", p_IdSucursal_fin) :
                new ObjectParameter("p_IdSucursal_fin", typeof(int));
    
            var p_IdBodega_iniParameter = p_IdBodega_ini.HasValue ?
                new ObjectParameter("p_IdBodega_ini", p_IdBodega_ini) :
                new ObjectParameter("p_IdBodega_ini", typeof(int));
    
            var p_IdBodega_finParameter = p_IdBodega_fin.HasValue ?
                new ObjectParameter("p_IdBodega_fin", p_IdBodega_fin) :
                new ObjectParameter("p_IdBodega_fin", typeof(int));
    
            var p_IdProducto_iniParameter = p_IdProducto_ini.HasValue ?
                new ObjectParameter("p_IdProducto_ini", p_IdProducto_ini) :
                new ObjectParameter("p_IdProducto_ini", typeof(decimal));
    
            var p_IdProducto_finParameter = p_IdProducto_fin.HasValue ?
                new ObjectParameter("p_IdProducto_fin", p_IdProducto_fin) :
                new ObjectParameter("p_IdProducto_fin", typeof(decimal));
    
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            var p_No_Mostrar_valores_en_0Parameter = p_No_Mostrar_valores_en_0.HasValue ?
                new ObjectParameter("p_No_Mostrar_valores_en_0", p_No_Mostrar_valores_en_0) :
                new ObjectParameter("p_No_Mostrar_valores_en_0", typeof(bool));
    
            var p_Mostrar_detalladoParameter = p_Mostrar_detallado.HasValue ?
                new ObjectParameter("p_Mostrar_detallado", p_Mostrar_detallado) :
                new ObjectParameter("p_Mostrar_detallado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt010_Result>("spINV_Rpt010", p_IdEmpresaParameter, p_IdSucursal_iniParameter, p_IdSucursal_finParameter, p_IdBodega_iniParameter, p_IdBodega_finParameter, p_IdProducto_iniParameter, p_IdProducto_finParameter, p_Fecha_iniParameter, p_Fecha_finParameter, p_IdUsuarioParameter, p_No_Mostrar_valores_en_0Parameter, p_Mostrar_detalladoParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt030_Result> spINV_Rpt030(Nullable<int> p_IdEmpresa, Nullable<int> p_IdSucursalIni, Nullable<int> p_IdSucursalFin, Nullable<int> p_IdBodegaIni, Nullable<int> p_IdBodegaFin, string p_IdCentroCosto, string p_IdSubCentroCosto, Nullable<int> p_IdMov_inven_tipoIni, Nullable<int> p_IdMov_inven_tipoFin, Nullable<decimal> p_IdProductoIni, Nullable<decimal> p_IdProductoFin, string p_TipoMov, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<bool> p_Considerar_saldo_inicial)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdSucursalIniParameter = p_IdSucursalIni.HasValue ?
                new ObjectParameter("p_IdSucursalIni", p_IdSucursalIni) :
                new ObjectParameter("p_IdSucursalIni", typeof(int));
    
            var p_IdSucursalFinParameter = p_IdSucursalFin.HasValue ?
                new ObjectParameter("p_IdSucursalFin", p_IdSucursalFin) :
                new ObjectParameter("p_IdSucursalFin", typeof(int));
    
            var p_IdBodegaIniParameter = p_IdBodegaIni.HasValue ?
                new ObjectParameter("p_IdBodegaIni", p_IdBodegaIni) :
                new ObjectParameter("p_IdBodegaIni", typeof(int));
    
            var p_IdBodegaFinParameter = p_IdBodegaFin.HasValue ?
                new ObjectParameter("p_IdBodegaFin", p_IdBodegaFin) :
                new ObjectParameter("p_IdBodegaFin", typeof(int));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdSubCentroCostoParameter = p_IdSubCentroCosto != null ?
                new ObjectParameter("p_IdSubCentroCosto", p_IdSubCentroCosto) :
                new ObjectParameter("p_IdSubCentroCosto", typeof(string));
    
            var p_IdMov_inven_tipoIniParameter = p_IdMov_inven_tipoIni.HasValue ?
                new ObjectParameter("p_IdMov_inven_tipoIni", p_IdMov_inven_tipoIni) :
                new ObjectParameter("p_IdMov_inven_tipoIni", typeof(int));
    
            var p_IdMov_inven_tipoFinParameter = p_IdMov_inven_tipoFin.HasValue ?
                new ObjectParameter("p_IdMov_inven_tipoFin", p_IdMov_inven_tipoFin) :
                new ObjectParameter("p_IdMov_inven_tipoFin", typeof(int));
    
            var p_IdProductoIniParameter = p_IdProductoIni.HasValue ?
                new ObjectParameter("p_IdProductoIni", p_IdProductoIni) :
                new ObjectParameter("p_IdProductoIni", typeof(decimal));
    
            var p_IdProductoFinParameter = p_IdProductoFin.HasValue ?
                new ObjectParameter("p_IdProductoFin", p_IdProductoFin) :
                new ObjectParameter("p_IdProductoFin", typeof(decimal));
    
            var p_TipoMovParameter = p_TipoMov != null ?
                new ObjectParameter("p_TipoMov", p_TipoMov) :
                new ObjectParameter("p_TipoMov", typeof(string));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_Considerar_saldo_inicialParameter = p_Considerar_saldo_inicial.HasValue ?
                new ObjectParameter("p_Considerar_saldo_inicial", p_Considerar_saldo_inicial) :
                new ObjectParameter("p_Considerar_saldo_inicial", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt030_Result>("spINV_Rpt030", p_IdEmpresaParameter, p_IdSucursalIniParameter, p_IdSucursalFinParameter, p_IdBodegaIniParameter, p_IdBodegaFinParameter, p_IdCentroCostoParameter, p_IdSubCentroCostoParameter, p_IdMov_inven_tipoIniParameter, p_IdMov_inven_tipoFinParameter, p_IdProductoIniParameter, p_IdProductoFinParameter, p_TipoMovParameter, p_FechaIniParameter, p_FechaFinParameter, p_Considerar_saldo_inicialParameter);
        }
    }
}
