//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesContabilidadRptGeneral : DbContext
    {
        public EntitiesContabilidadRptGeneral()
            : base("name=EntitiesContabilidadRptGeneral")
        {
        }
        
        //poner esta funcion dentro de la clase entities no viene por defecto
        //10000 timeout 1 minutos
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCONTA_Rpt004> vwCONTA_Rpt004 { get; set; }
        public DbSet<vwCONTA_Rpt005> vwCONTA_Rpt005 { get; set; }
        public DbSet<vwCONTA_Rpt009> vwCONTA_Rpt009 { get; set; }
        public DbSet<vwCONTA_Rpt003> vwCONTA_Rpt003 { get; set; }
        public DbSet<vwCONTA_Rpt008> vwCONTA_Rpt008 { get; set; }
        public DbSet<vwCONTA_Rpt014> vwCONTA_Rpt014 { get; set; }
        public DbSet<ct_centro_costo_Filtro> ct_centro_costo_Filtro { get; set; }
        public DbSet<vwCONTA_Rpt001> vwCONTA_Rpt001 { get; set; }
        public DbSet<vwCONTA_Rpt002> vwCONTA_Rpt002 { get; set; }
        public DbSet<vwCONTA_Rpt024> vwCONTA_Rpt024 { get; set; }
    
        public virtual int spCON_Saldo_Inicial_x_cta_cble(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaCorte, string p_IdCentroCosto)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaCorteParameter = p_FechaCorte.HasValue ?
                new ObjectParameter("p_FechaCorte", p_FechaCorte) :
                new ObjectParameter("p_FechaCorte", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCON_Saldo_Inicial_x_cta_cble", p_IdEmpresaParameter, p_FechaCorteParameter, p_IdCentroCostoParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt009_Result> spCONTA_Rpt009(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_IdPunto_cargo_grupo)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt009_Result>("spCONTA_Rpt009", p_IdEmpresaParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdPunto_cargo_grupoParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt007_Result> spCONTA_Rpt007(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, string p_IdCentroCosto, Nullable<int> p_IdPunto_cargo_grupo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_mostrar_cero)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_mostrar_ceroParameter = p_mostrar_cero.HasValue ?
                new ObjectParameter("p_mostrar_cero", p_mostrar_cero) :
                new ObjectParameter("p_mostrar_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt007_Result>("spCONTA_Rpt007", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdCentroCostoParameter, p_IdPunto_cargo_grupoParameter, p_IdPunto_cargoParameter, p_mostrar_ceroParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt016_Result> spCONTA_Rpt016(Nullable<int> p_IdEmpresa, Nullable<int> p_IdPeriodo, Nullable<bool> p_Mostrar_CC)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdPeriodoParameter = p_IdPeriodo.HasValue ?
                new ObjectParameter("p_IdPeriodo", p_IdPeriodo) :
                new ObjectParameter("p_IdPeriodo", typeof(int));
    
            var p_Mostrar_CCParameter = p_Mostrar_CC.HasValue ?
                new ObjectParameter("p_Mostrar_CC", p_Mostrar_CC) :
                new ObjectParameter("p_Mostrar_CC", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt016_Result>("spCONTA_Rpt016", p_IdEmpresaParameter, p_IdPeriodoParameter, p_Mostrar_CCParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt016_cuentas_x_anio_Result> spCONTA_Rpt016_cuentas_x_anio(Nullable<int> p_IdEmpresa, Nullable<int> p_Anio, Nullable<bool> p_Mostrar_CC)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_AnioParameter = p_Anio.HasValue ?
                new ObjectParameter("p_Anio", p_Anio) :
                new ObjectParameter("p_Anio", typeof(int));
    
            var p_Mostrar_CCParameter = p_Mostrar_CC.HasValue ?
                new ObjectParameter("p_Mostrar_CC", p_Mostrar_CC) :
                new ObjectParameter("p_Mostrar_CC", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt016_cuentas_x_anio_Result>("spCONTA_Rpt016_cuentas_x_anio", p_IdEmpresaParameter, p_AnioParameter, p_Mostrar_CCParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt018_Result> spCONTA_Rpt018(Nullable<System.DateTime> p_Fecha_ini, Nullable<System.DateTime> p_Fecha_fin, Nullable<int> p_IdEmpresa, Nullable<int> p_IdPunto_cargo_grupo_ini, Nullable<int> p_IdPunto_cargo_grupo_fin, Nullable<bool> p_Mostrar_detalle)
        {
            var p_Fecha_iniParameter = p_Fecha_ini.HasValue ?
                new ObjectParameter("p_Fecha_ini", p_Fecha_ini) :
                new ObjectParameter("p_Fecha_ini", typeof(System.DateTime));
    
            var p_Fecha_finParameter = p_Fecha_fin.HasValue ?
                new ObjectParameter("p_Fecha_fin", p_Fecha_fin) :
                new ObjectParameter("p_Fecha_fin", typeof(System.DateTime));
    
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdPunto_cargo_grupo_iniParameter = p_IdPunto_cargo_grupo_ini.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo_ini", p_IdPunto_cargo_grupo_ini) :
                new ObjectParameter("p_IdPunto_cargo_grupo_ini", typeof(int));
    
            var p_IdPunto_cargo_grupo_finParameter = p_IdPunto_cargo_grupo_fin.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo_fin", p_IdPunto_cargo_grupo_fin) :
                new ObjectParameter("p_IdPunto_cargo_grupo_fin", typeof(int));
    
            var p_Mostrar_detalleParameter = p_Mostrar_detalle.HasValue ?
                new ObjectParameter("p_Mostrar_detalle", p_Mostrar_detalle) :
                new ObjectParameter("p_Mostrar_detalle", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt018_Result>("spCONTA_Rpt018", p_Fecha_iniParameter, p_Fecha_finParameter, p_IdEmpresaParameter, p_IdPunto_cargo_grupo_iniParameter, p_IdPunto_cargo_grupo_finParameter, p_Mostrar_detalleParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt010_Result> spCONTA_Rpt010(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_IdPunto_cargo_grupo, Nullable<bool> p_Mostrar_reg_cero)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_Mostrar_reg_ceroParameter = p_Mostrar_reg_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_cero", p_Mostrar_reg_cero) :
                new ObjectParameter("p_Mostrar_reg_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt010_Result>("spCONTA_Rpt010", p_IdEmpresaParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdPunto_cargo_grupoParameter, p_Mostrar_reg_ceroParameter);
        }
    
        public virtual ObjectResult<spCON_Mayorizar_x_fecha_corte_Result> spCON_Mayorizar_x_fecha_corte(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, string p_IdCentroCosto, Nullable<int> p_IdPunto_cargo_grupo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_reg_en_cero, Nullable<bool> p_Mostrar_reg_Centro_costo, Nullable<bool> p_Considerar_Asiento_cierre_anual, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            var p_Mostrar_reg_Centro_costoParameter = p_Mostrar_reg_Centro_costo.HasValue ?
                new ObjectParameter("p_Mostrar_reg_Centro_costo", p_Mostrar_reg_Centro_costo) :
                new ObjectParameter("p_Mostrar_reg_Centro_costo", typeof(bool));
    
            var p_Considerar_Asiento_cierre_anualParameter = p_Considerar_Asiento_cierre_anual.HasValue ?
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", p_Considerar_Asiento_cierre_anual) :
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCON_Mayorizar_x_fecha_corte_Result>("spCON_Mayorizar_x_fecha_corte", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdCentroCostoParameter, p_IdPunto_cargo_grupoParameter, p_IdPunto_cargoParameter, p_Mostrar_reg_en_ceroParameter, p_Mostrar_reg_Centro_costoParameter, p_Considerar_Asiento_cierre_anualParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt006_Result> spCONTA_Rpt006(Nullable<int> p_IdEmpresa, string p_IdCtaCble, string p_IdCentro_Costo, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_IdGrupo_Punto_cargo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_Asiento_Cierre)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdCtaCbleParameter = p_IdCtaCble != null ?
                new ObjectParameter("p_IdCtaCble", p_IdCtaCble) :
                new ObjectParameter("p_IdCtaCble", typeof(string));
    
            var p_IdCentro_CostoParameter = p_IdCentro_Costo != null ?
                new ObjectParameter("p_IdCentro_Costo", p_IdCentro_Costo) :
                new ObjectParameter("p_IdCentro_Costo", typeof(string));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdGrupo_Punto_cargoParameter = p_IdGrupo_Punto_cargo.HasValue ?
                new ObjectParameter("p_IdGrupo_Punto_cargo", p_IdGrupo_Punto_cargo) :
                new ObjectParameter("p_IdGrupo_Punto_cargo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_Asiento_CierreParameter = p_Mostrar_Asiento_Cierre.HasValue ?
                new ObjectParameter("p_Mostrar_Asiento_Cierre", p_Mostrar_Asiento_Cierre) :
                new ObjectParameter("p_Mostrar_Asiento_Cierre", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt006_Result>("spCONTA_Rpt006", p_IdEmpresaParameter, p_IdCtaCbleParameter, p_IdCentro_CostoParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdGrupo_Punto_cargoParameter, p_IdPunto_cargoParameter, p_Mostrar_Asiento_CierreParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt023_Result> spCONTA_Rpt023(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, Nullable<int> p_IdPunto_cargo_grupo, Nullable<bool> p_Mostrar_reg_en_cero, Nullable<bool> p_Considerar_Asiento_cierre_anual, string p_IdUsuario, string p_TipoBalance)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            var p_Considerar_Asiento_cierre_anualParameter = p_Considerar_Asiento_cierre_anual.HasValue ?
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", p_Considerar_Asiento_cierre_anual) :
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            var p_TipoBalanceParameter = p_TipoBalance != null ?
                new ObjectParameter("p_TipoBalance", p_TipoBalance) :
                new ObjectParameter("p_TipoBalance", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt023_Result>("spCONTA_Rpt023", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdPunto_cargo_grupoParameter, p_Mostrar_reg_en_ceroParameter, p_Considerar_Asiento_cierre_anualParameter, p_IdUsuarioParameter, p_TipoBalanceParameter);
        }
    
        public virtual ObjectResult<spCONTA_Rpt006_Poli_Result> spCONTA_Rpt006_Poli(Nullable<int> p_IdEmpresa, string p_IdCtaCble, string p_IdCentro_Costo, Nullable<System.DateTime> p_FechaIni, Nullable<System.DateTime> p_FechaFin, Nullable<int> p_IdGrupo_Punto_cargo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_Asiento_Cierre)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_IdCtaCbleParameter = p_IdCtaCble != null ?
                new ObjectParameter("p_IdCtaCble", p_IdCtaCble) :
                new ObjectParameter("p_IdCtaCble", typeof(string));
    
            var p_IdCentro_CostoParameter = p_IdCentro_Costo != null ?
                new ObjectParameter("p_IdCentro_Costo", p_IdCentro_Costo) :
                new ObjectParameter("p_IdCentro_Costo", typeof(string));
    
            var p_FechaIniParameter = p_FechaIni.HasValue ?
                new ObjectParameter("p_FechaIni", p_FechaIni) :
                new ObjectParameter("p_FechaIni", typeof(System.DateTime));
    
            var p_FechaFinParameter = p_FechaFin.HasValue ?
                new ObjectParameter("p_FechaFin", p_FechaFin) :
                new ObjectParameter("p_FechaFin", typeof(System.DateTime));
    
            var p_IdGrupo_Punto_cargoParameter = p_IdGrupo_Punto_cargo.HasValue ?
                new ObjectParameter("p_IdGrupo_Punto_cargo", p_IdGrupo_Punto_cargo) :
                new ObjectParameter("p_IdGrupo_Punto_cargo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_Asiento_CierreParameter = p_Mostrar_Asiento_Cierre.HasValue ?
                new ObjectParameter("p_Mostrar_Asiento_Cierre", p_Mostrar_Asiento_Cierre) :
                new ObjectParameter("p_Mostrar_Asiento_Cierre", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCONTA_Rpt006_Poli_Result>("spCONTA_Rpt006_Poli", p_IdEmpresaParameter, p_IdCtaCbleParameter, p_IdCentro_CostoParameter, p_FechaIniParameter, p_FechaFinParameter, p_IdGrupo_Punto_cargoParameter, p_IdPunto_cargoParameter, p_Mostrar_Asiento_CierreParameter);
        }
    
        public virtual ObjectResult<spCON_Mayorizar_x_Rangofecha_Result> spCON_Mayorizar_x_Rangofecha(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, string p_IdCentroCosto, Nullable<int> p_IdPunto_cargo_grupo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_reg_en_cero, Nullable<bool> p_Mostrar_reg_Centro_costo, Nullable<bool> p_Considerar_Asiento_cierre_anual, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            var p_Mostrar_reg_Centro_costoParameter = p_Mostrar_reg_Centro_costo.HasValue ?
                new ObjectParameter("p_Mostrar_reg_Centro_costo", p_Mostrar_reg_Centro_costo) :
                new ObjectParameter("p_Mostrar_reg_Centro_costo", typeof(bool));
    
            var p_Considerar_Asiento_cierre_anualParameter = p_Considerar_Asiento_cierre_anual.HasValue ?
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", p_Considerar_Asiento_cierre_anual) :
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCON_Mayorizar_x_Rangofecha_Result>("spCON_Mayorizar_x_Rangofecha", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdCentroCostoParameter, p_IdPunto_cargo_grupoParameter, p_IdPunto_cargoParameter, p_Mostrar_reg_en_ceroParameter, p_Mostrar_reg_Centro_costoParameter, p_Considerar_Asiento_cierre_anualParameter, p_IdUsuarioParameter);
        }
    }
}
