//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_ActivoFijo_Reportes : DbContext
    {
        public Entities_ActivoFijo_Reportes()
            : base("name=Entities_ActivoFijo_Reportes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwACTF_Rpt002> vwACTF_Rpt002 { get; set; }
        public DbSet<vwACTF_Rpt003> vwACTF_Rpt003 { get; set; }
        public DbSet<vwACTF_Rpt004> vwACTF_Rpt004 { get; set; }
        public DbSet<vwACTF_Rpt005> vwACTF_Rpt005 { get; set; }
        public DbSet<vwACTF_Rpt006> vwACTF_Rpt006 { get; set; }
        public DbSet<vwACTF_Rpt007> vwACTF_Rpt007 { get; set; }
        public DbSet<vwACTF_Rpt008> vwACTF_Rpt008 { get; set; }
        public DbSet<vwACTF_Rpt009> vwACTF_Rpt009 { get; set; }
        public DbSet<vwACTF_Rpt010> vwACTF_Rpt010 { get; set; }
        public DbSet<vwACTF_Rpt011> vwACTF_Rpt011 { get; set; }
        public DbSet<vwACTF_Rpt013> vwACTF_Rpt013 { get; set; }
        public DbSet<vwACTF_Rpt001> vwACTF_Rpt001 { get; set; }
        public DbSet<vwACTF_Rpt012> vwACTF_Rpt012 { get; set; }
        public DbSet<vwACTF_Rpt014> vwACTF_Rpt014 { get; set; }
        public DbSet<vwACTF_Rpt014_1> vwACTF_Rpt014_1 { get; set; }
        public DbSet<vwACTF_Rpt015> vwACTF_Rpt015 { get; set; }
        public DbSet<vwACTF_Rpt016> vwACTF_Rpt016 { get; set; }
    
        public virtual ObjectResult<spACTF_Rpt012_Result> spACTF_Rpt012(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_corte, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_corteParameter = p_Fecha_corte.HasValue ?
                new ObjectParameter("p_Fecha_corte", p_Fecha_corte) :
                new ObjectParameter("p_Fecha_corte", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spACTF_Rpt012_Result>("spACTF_Rpt012", p_IdEmpresaParameter, p_Fecha_corteParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spACTF_Rpt014_Result> spACTF_Rpt014(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_corte, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_corteParameter = p_Fecha_corte.HasValue ?
                new ObjectParameter("p_Fecha_corte", p_Fecha_corte) :
                new ObjectParameter("p_Fecha_corte", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spACTF_Rpt014_Result>("spACTF_Rpt014", p_IdEmpresaParameter, p_Fecha_corteParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spACTF_Rpt012_Poli_Result> spACTF_Rpt012_Poli(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_corte, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_corteParameter = p_Fecha_corte.HasValue ?
                new ObjectParameter("p_Fecha_corte", p_Fecha_corte) :
                new ObjectParameter("p_Fecha_corte", typeof(System.DateTime));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spACTF_Rpt012_Poli_Result>("spACTF_Rpt012_Poli", p_IdEmpresaParameter, p_Fecha_corteParameter, p_IdUsuarioParameter);
        }
    }
}
