//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBAN_Rpt007
    {
        public Nullable<int> IdEmpresa_cxp { get; set; }
        public Nullable<int> IdTipoCbte_cxp { get; set; }
        public string Tipo_cbte_cxp { get; set; }
        public Nullable<decimal> IdCbteCble_cxp { get; set; }
        public int IdEmpresa_pago { get; set; }
        public int IdTipoCbte_pago { get; set; }
        public string Tipo_cbte_pago { get; set; }
        public decimal IdCbteCble_pago { get; set; }
        public string co_observacion { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public decimal IdTipoFlujo { get; set; }
        public string nom_tipo_flujo { get; set; }
        public string cod_flujo { get; set; }
        public string Tipo { get; set; }
        public double dc_Valor { get; set; }
        public int IdBanco { get; set; }
        public string nom_banco { get; set; }
        public string Tipo_movi { get; set; }
        public long orden { get; set; }
        public string pe_nombreCompleto { get; set; }
        public long en_conci { get; set; }
    }
}
