//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCOMP_Rpt004
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public string documento { get; set; }
        public System.DateTime oc_fecha { get; set; }
        public string oc_observacion { get; set; }
        public decimal IdComprador { get; set; }
        public string nom_comprador { get; set; }
        public decimal IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public string IdEstadoAprobacion_cat { get; set; }
        public Nullable<int> IdMotivo { get; set; }
        public string Nom_motivo_oc { get; set; }
        public decimal IdProducto { get; set; }
        public string nom_producto { get; set; }
        public double do_Cantidad { get; set; }
        public double precio { get; set; }
        public double do_subtotal { get; set; }
        public double do_iva { get; set; }
        public double do_total { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string nom_punto_cargo { get; set; }
        public string IdCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string sub_centro_costo { get; set; }
    }
}
