//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCONTA_Rpt024
    {
        public int IdEmpresa { get; set; }
        public string Tipo { get; set; }
        public decimal NumDiario { get; set; }
        public string IdCtaCble { get; set; }
        public string Cuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime cb_FechaTransac { get; set; }
        public double Debe { get; set; }
        public double Haber { get; set; }
        public string Observacion { get; set; }
        public string IdUsuario { get; set; }
        public string IdCentroCosto { get; set; }
    }
}
