//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCOMP_Rpt013
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdProducto { get; set; }
        public string em_nombre { get; set; }
        public string pr_nombre { get; set; }
        public int oc_plazo { get; set; }
        public System.DateTime oc_fecha { get; set; }
        public string pr_codigo { get; set; }
        public double do_Cantidad { get; set; }
        public double CantidadRecibida { get; set; }
        public double Saldo { get; set; }
        public string IdUnidadMedida { get; set; }
        public string pr_descripcion { get; set; }
        public string IdCategoria { get; set; }
        public string nom_categoria { get; set; }
        public int IdLinea { get; set; }
        public string nom_linea { get; set; }
        public double pr_peso { get; set; }
        public double do_precioCompra { get; set; }
        public double do_subtotal { get; set; }
        public double do_Subtotal_SinDescuento { get; set; }
        public double do_iva { get; set; }
        public double do_total { get; set; }
        public double do_descuento { get; set; }
        public double do_porc_des { get; set; }
        public string pr_contribuyenteEspecial { get; set; }
        public string oc_NumDocumento { get; set; }
        public string Usuario_Solicitante { get; set; }
        public string Usuario_Procesa { get; set; }
        public string Usuario_Aprueba { get; set; }
        public string TerminoPago { get; set; }
        public int DiasTerminoPago { get; set; }
        public string UnidadMedidaConsumo { get; set; }
        public string IdCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string detalle_x_item { get; set; }
        public string oc_observacion { get; set; }
        public string IdEstadoAprobacion_cat { get; set; }
        public string Estado { get; set; }
    }
}
