//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_Rpt014
    {
        public int IdMarca { get; set; }
        public string marca { get; set; }
        public int IdGrupo { get; set; }
        public string nom_grupo { get; set; }
        public Nullable<double> vt_Peso { get; set; }
        public Nullable<double> vt_cantidad { get; set; }
        public Nullable<double> vt_total { get; set; }
        public Nullable<double> vt_DescUnitario { get; set; }
        public Nullable<double> vt_PorDescUnitario { get; set; }
        public Nullable<double> vt_PrecioFinal { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public Nullable<double> vt_Subtotal { get; set; }
        public Nullable<double> vt_iva { get; set; }
        public Nullable<double> vt_por_iva { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<double> mv_costo { get; set; }
    }
}
