//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorPagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_cp_retencion_x_empresa
    {
        public int IdEmpresa { get; set; }
        public string em_ruc { get; set; }
        public string serie { get; set; }
        public string NumRetencion { get; set; }
    }
}
