//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Compra
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_cotizacion_compra_GE_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdCotizacion { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> Idproducto { get; set; }
        public Nullable<double> Cant_soli { get; set; }
        public Nullable<double> Cant_a_cotizar { get; set; }
        public string Observacion { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
        public string IdCod_Impuesto { get; set; }
        public Nullable<decimal> Porce_Iva { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> do_precioCompra { get; set; }
        public Nullable<decimal> do_porc_des { get; set; }
        public Nullable<decimal> do_descuento { get; set; }
        public Nullable<decimal> do_subtotal { get; set; }
        public Nullable<decimal> do_total { get; set; }
        public string do_observacion { get; set; }
    }
}
