//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Compra
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_SolicitudCompra_Det_SaldoPendiente
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string Sucursal { get; set; }
        public decimal IdSolicitudCompra { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime fecha { get; set; }
        public int plazo { get; set; }
        public System.DateTime fecha_vtc { get; set; }
        public string observacion { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string nom_Proyecto { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public string cod_Oferta { get; set; }
        public string nom_Oferta { get; set; }
        public decimal IdSolicitante { get; set; }
        public string nom_solicitante { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public string do_observacion { get; set; }
        public string IdUnidadMedida { get; set; }
        public string UnidadMedida { get; set; }
        public string UnidadMedida_Alterno { get; set; }
        public double do_Cantidad { get; set; }
        public Nullable<double> CantidadPedida { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string IdCategoria { get; set; }
        public string ca_Categoria { get; set; }
        public int IdLinea { get; set; }
        public string nom_linea { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public Nullable<int> Secuencia_Oferta { get; set; }
        public string cod_Rubro { get; set; }
        public string nom_Rubro { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa_obr_AsignacionPorcentual { get; set; }
        public Nullable<int> IdSucursal_obr_AsignacionPorcentual { get; set; }
        public Nullable<int> IdProyecto_obr_AsignacionPorcentual { get; set; }
        public Nullable<int> IdOferta_obr_AsignacionPorcentual { get; set; }
        public Nullable<int> Secuencia_obr_AsignacionPorcentual { get; set; }
        public string Descripcion_AsignacionPorcentual { get; set; }
        public Nullable<double> Porcentaje_AsignacionPorcentual { get; set; }
        public Nullable<double> Valor_AsignacionPorcentual { get; set; }
    }
}
