//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Archivo_Transferencia_Det
    {
        public int IdEmpresa { get; set; }
        public decimal IdArchivo { get; set; }
        public int Secuencia { get; set; }
        public string IdProceso_bancario { get; set; }
        public string Origen_Archivo { get; set; }
        public string pe_cedulaRuc { get; set; }
        public Nullable<int> IdBanco_acreditacion { get; set; }
        public string IdTipoCta_acreditacion_cat { get; set; }
        public string num_cta_acreditacion { get; set; }
        public string IdTipoDocumento_acreditacion { get; set; }
        public string cedulaRuc_acreditacion { get; set; }
        public string beneficiario_acreditacion { get; set; }
        public string correo_acreditacion { get; set; }
        public string pe_nombreCompleto { get; set; }
        public Nullable<int> IdEmpresa_OP { get; set; }
        public Nullable<decimal> IdOrdenPago { get; set; }
        public Nullable<int> Secuencia_OP { get; set; }
        public string Referencia { get; set; }
        public decimal Valor { get; set; }
        public decimal Valor_cobrado { get; set; }
        public decimal Saldo { get; set; }
        public string IdEstadoRegistro_cat { get; set; }
        public string nom_EstadoRegistro_cat { get; set; }
        public string Id_Item { get; set; }
        public string IdOrden_Bancaria { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdBanco { get; set; }
        public Nullable<decimal> Secuencial_reg_x_proceso { get; set; }
        public Nullable<int> IdEmpresa_pago { get; set; }
        public Nullable<int> IdTipoCbte_pago { get; set; }
        public Nullable<decimal> IdCbteCble_pago { get; set; }
        public string cb_Estado { get; set; }
        public string CodPersona { get; set; }
        public Nullable<int> IdInstitucion_contrato { get; set; }
        public Nullable<decimal> idContrato { get; set; }
        public Nullable<int> IdEmpresaNomina { get; set; }
        public Nullable<int> IdNominaTipo { get; set; }
        public Nullable<int> IdNominaTipoLiqui { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public string IdRubro { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
