//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorPagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_CXP_EDEHSA_Rpt001_Saldo_Inicial
    {
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public string IdUsuario { get; set; }
        public string nom_proveedor { get; set; }
        public double Saldo_inicial { get; set; }
        public double Debitos { get; set; }
        public double Creditos { get; set; }
        public double Saldo { get; set; }
        public string descripcion_clas_prove { get; set; }
        public int IdClaseProveedor { get; set; }
    }
}
