//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorPagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_nota_DebCre_Aprobacion_Ing_Bod_x_OC
    {
        public int IdEmpresa { get; set; }
        public decimal IdAprobacion { get; set; }
        public System.DateTime FechaAprobacion { get; set; }
        public Nullable<int> IdEmpresa_Nota { get; set; }
        public Nullable<decimal> IdCbteCble_Nota { get; set; }
        public Nullable<int> IdTipoCbte_Nota { get; set; }
        public double Subtotal_iva { get; set; }
        public double Subtotal_siniva { get; set; }
        public double Descuento { get; set; }
        public double BaseImponible { get; set; }
        public double Por_iva { get; set; }
        public double Valor_iva { get; set; }
        public double Total { get; set; }
    }
}
