//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.CuentaPorPagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_base_retenciones
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public System.DateTime Fecha { get; set; }
        public double BASE_IVA { get; set; }
        public double BASE_IVA0 { get; set; }
        public double BASE { get; set; }
        public int IdCodigo_SRI { get; set; }
        public string re_tipoRet { get; set; }
        public double re_valor_retencion { get; set; }
    }
}
