//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Mail
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mail
    {
        public mail_Mail()
        {
            this.mail_Mail_Attachment = new HashSet<mail_Mail_Attachment>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdMail { get; set; }
        public string IdUsuario { get; set; }
        public string Origen { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public Nullable<bool> IsBodyHtml { get; set; }
        public string Para { get; set; }
        public string CC { get; set; }
        public string MensajeError { get; set; }
    
        public virtual ICollection<mail_Mail_Attachment> mail_Mail_Attachment { get; set; }
    }
}
