//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.ActivoFijo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Af_proceso_depreciacion
    {
        public int IdEmpresa { get; set; }
        public int IdActivoFijo { get; set; }
        public string IdUsuario { get; set; }
        public double Af_costo_compra { get; set; }
        public double Af_depreciacion_acum { get; set; }
        public double Af_valor_depreciacion { get; set; }
    
        public virtual Af_Activo_fijo Af_Activo_fijo { get; set; }
    }
}
