//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.ActivoFijo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAf_Depre_x_Ciclo_Valor
    {
        public int IdEmpresa { get; set; }
        public decimal IdDepreciacion { get; set; }
        public int IdTipoDepreciacion { get; set; }
        public int IdActivoFijo { get; set; }
        public long Ciclo { get; set; }
        public Nullable<double> Valor_Depreciacion_Acum { get; set; }
        public bool Es_Activo_x_Mejora { get; set; }
    }
}
