//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Actividades_Horario_Acciones
    {
        public string IdTransaccion { get; set; }
        public string IdAccion { get; set; }
        public string Descripcion { get; set; }
        public int TiempoEspera { get; set; }
        public int Secuencia_ejecucion { get; set; }
    
        public virtual tb_Actividades_Horario tb_Actividades_Horario { get; set; }
    }
}
