//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Compra
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_Registro_OrdenComprax_Cotizacion
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public decimal IdCotizacion { get; set; }
        public decimal SecuenciaDetalleCotizacion { get; set; }
        public bool estado { get; set; }
    }
}
