//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Compra
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_solicitud_compra_X_Orden_Compra
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdSolicitudCompra { get; set; }
        public string NumDocumento { get; set; }
        public decimal IdPersona_Solicita { get; set; }
        public System.DateTime fecha { get; set; }
        public int plazo { get; set; }
        public System.DateTime fecha_vtc { get; set; }
        public string observacion { get; set; }
        public string Estado { get; set; }
        public string Sucursal { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public string nom_EstadoAprobacion { get; set; }
        public string IdUsuarioAprobo { get; set; }
        public string MotivoAprobacion { get; set; }
        public Nullable<System.DateTime> FechaHoraAprobacion { get; set; }
        public string Solicitante { get; set; }
    }
}
