//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Cbte_Ban_Edehsa
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipocbte { get; set; }
        public decimal IdOrdenPago { get; set; }
        public int secuencia { get; set; }
    }
}
