//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_parametro
    {
        public int IdEmpresa { get; set; }
        public string IdEstadoAprobacion_OC { get; set; }
        public int IdMovi_inven_tipo_OC { get; set; }
        public string IdEstadoAnulacion_OC { get; set; }
        public int IdMovi_inven_tipo_dev_compra { get; set; }
        public string IdEstadoAprobacion_SolCompra { get; set; }
        public int IdSucursal_x_Aprob_x_SolComp { get; set; }
        public string IdEstado_cierre { get; set; }
        public Nullable<int> default_dias_plazo { get; set; }
        public Nullable<int> default_dias_vencidos { get; set; }
        public Nullable<bool> NotificaAprobacionOC { get; set; }
        public Nullable<bool> NotificaAprobacionOCAuto { get; set; }
    
        public virtual com_catalogo com_catalogo { get; set; }
        public virtual com_catalogo com_catalogo1 { get; set; }
        public virtual com_catalogo com_catalogo2 { get; set; }
        public virtual com_estado_cierre com_estado_cierre { get; set; }
    }
}
