//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_nota_DebCre_x_com_ordencompra_local
    {
        public int ndc_IdEmpresa { get; set; }
        public decimal ndc_IdCbteCble_Nota { get; set; }
        public int ndc_IdTipoCbte_Nota { get; set; }
        public int com_IdEmpresa { get; set; }
        public int com_IdSucursal { get; set; }
        public decimal com_IdOrdenCompraLocal { get; set; }
        public string og_Observacion { get; set; }
    
        public virtual cp_nota_DebCre cp_nota_DebCre { get; set; }
    }
}
