//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_orden_pago_x_empleado_x_nomina_x_periodo
    {
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPago { get; set; }
        public decimal IdPersona { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<decimal> IdTipoFlujo { get; set; }
        public string IdTipo_op { get; set; }
        public Nullable<double> Valor { get; set; }
        public string Estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Trasanc { get; set; }
        public string IdUsuarioUltModificacion { get; set; }
        public Nullable<System.DateTime> Fecha_UltModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public string MotivoAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    
        public virtual cp_orden_pago cp_orden_pago { get; set; }
    }
}
