//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_proveedor_datos_acreditacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string IdTipoCuenta { get; set; }
        public string NumeroCuenta { get; set; }
        public string IdTipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public string Beneficiario { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Predefinida { get; set; }
    }
}
