//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_anio_fiscal_x_cuenta_utilidad
    {
        public int idempresa { get; set; }
        public int idaniofiscal { get; set; }
        public string idctacble { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idempresa_cbte_cierre { get; set; }
        public Nullable<int> idtipocbte_cbte_cierre { get; set; }
        public Nullable<decimal> idcbtecble_cbte_cierre { get; set; }
    }
}
