//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_anio_fiscal
    {
        public int idaniofiscal { get; set; }
        public System.DateTime af_fechaini { get; set; }
        public System.DateTime af_fechafin { get; set; }
        public string af_estado { get; set; }
    }
}
