//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_cbtecble
    {
        public ct_cbtecble()
        {
            this.ct_anio_fiscal_x_cuenta_utilidad = new HashSet<ct_anio_fiscal_x_cuenta_utilidad>();
            this.ct_cbtecble_det = new HashSet<ct_cbtecble_det>();
            this.ct_cbtecble_reversado1 = new HashSet<ct_cbtecble_reversado>();
        }
    
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public string codcbtecble { get; set; }
        public int idperiodo { get; set; }
        public System.DateTime cb_fecha { get; set; }
        public double cb_valor { get; set; }
        public string cb_observacion { get; set; }
        public decimal cb_secuencia { get; set; }
        public string cb_estado { get; set; }
        public int cb_anio { get; set; }
        public int cb_mes { get; set; }
        public string idusuario { get; set; }
        public string idusuarioanu { get; set; }
        public string cb_motivoanu { get; set; }
        public string idusuarioultmodi { get; set; }
        public Nullable<System.DateTime> cb_fechaanu { get; set; }
        public System.DateTime cb_fechatransac { get; set; }
        public Nullable<System.DateTime> cb_fechaultmodi { get; set; }
        public string cb_mayorizado { get; set; }
        public bool cb_para_conciliar { get; set; }
        public int idsucursal { get; set; }
    
        public virtual ICollection<ct_anio_fiscal_x_cuenta_utilidad> ct_anio_fiscal_x_cuenta_utilidad { get; set; }
        public virtual ct_cbtecble_tipo ct_cbtecble_tipo { get; set; }
        public virtual ICollection<ct_cbtecble_det> ct_cbtecble_det { get; set; }
        public virtual ct_cbtecble_reversado ct_cbtecble_reversado { get; set; }
        public virtual ICollection<ct_cbtecble_reversado> ct_cbtecble_reversado1 { get; set; }
    }
}
