//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_centro_costo
    {
        public ct_centro_costo()
        {
            this.ct_cbtecble_det = new HashSet<ct_cbtecble_det>();
        }
    
        public int idempresa { get; set; }
        public string idcentrocosto { get; set; }
        public string codcentrocosto { get; set; }
        public string centro_costo { get; set; }
        public string idcentrocostopadre { get; set; }
        public Nullable<decimal> idcatalogo { get; set; }
        public string pc_esmovimiento { get; set; }
        public int idnivel { get; set; }
        public string pc_estado { get; set; }
        public string idctacble { get; set; }
        public Nullable<System.DateTime> fecha_transac { get; set; }
        public string idusuario { get; set; }
        public string idusuarioultmod { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motivoanulacion { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    
        public virtual ICollection<ct_cbtecble_det> ct_cbtecble_det { get; set; }
    }
}
