//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_cbtecble
    {
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public string codcbtecble { get; set; }
        public int idperiodo { get; set; }
        public System.DateTime cb_fecha { get; set; }
        public double cb_valor { get; set; }
        public string cb_observacion { get; set; }
        public decimal cb_secuencia { get; set; }
        public string cb_estado { get; set; }
        public int cb_anio { get; set; }
        public int cb_mes { get; set; }
        public string idusuario { get; set; }
        public string idusuarioanu { get; set; }
        public string cb_motivoanu { get; set; }
        public string idusuarioultmodi { get; set; }
        public Nullable<System.DateTime> cb_fechaanu { get; set; }
        public System.DateTime cb_fechatransac { get; set; }
        public Nullable<System.DateTime> cb_fechaultmodi { get; set; }
        public string cb_mayorizado { get; set; }
        public bool cb_para_conciliar { get; set; }
        public int idsucursal { get; set; }
    }
}
