//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_cbtecble_det
    {
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public int secuencia { get; set; }
        public string idctacble { get; set; }
        public string idcentrocosto { get; set; }
        public string idcentrocosto_sub_centro_costo { get; set; }
        public double dc_valor { get; set; }
        public string dc_observacion { get; set; }
        public Nullable<decimal> dc_numconciliacion { get; set; }
        public string dc_estaconciliado { get; set; }
        public Nullable<int> idpunto_cargo { get; set; }
        public Nullable<int> idpunto_cargo_grupo { get; set; }
        public Nullable<bool> dc_para_conciliar { get; set; }
    
        public virtual ct_cbtecble ct_cbtecble { get; set; }
        public virtual ct_centro_costo ct_centro_costo { get; set; }
        public virtual ct_plancta ct_plancta { get; set; }
    }
}
