//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_cbtecble_tipo
    {
        public ct_cbtecble_tipo()
        {
            this.ct_cbtecble = new HashSet<ct_cbtecble>();
        }
    
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public string codtipocbte { get; set; }
        public string tc_tipocbte { get; set; }
        public string tc_estado { get; set; }
        public string tc_interno { get; set; }
        public string tc_nemonico { get; set; }
        public Nullable<int> idtipocbte_anul { get; set; }
        public string idusuario { get; set; }
        public Nullable<System.DateTime> fecha_transac { get; set; }
        public string idusuarioultmod { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motianula { get; set; }
    
        public virtual ICollection<ct_cbtecble> ct_cbtecble { get; set; }
    }
}
