//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_grupocble
    {
        public ct_grupocble()
        {
            this.ct_plancta = new HashSet<ct_plancta>();
        }
    
        public string idgrupocble { get; set; }
        public string gc_grupocble { get; set; }
        public byte gc_orden { get; set; }
        public string gc_estado_financiero { get; set; }
        public Nullable<int> gc_signo_operacion { get; set; }
        public string estado { get; set; }
        public string idgrupo_mayor { get; set; }
    
        public virtual ICollection<ct_plancta> ct_plancta { get; set; }
    }
}
