//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_parametro
    {
        public int idempresa { get; set; }
        public Nullable<int> idtipocbte_saldoinicial { get; set; }
        public Nullable<int> idtipocbte_asientocierre_anual { get; set; }
        public Nullable<bool> p_se_muestra_todas_las_ctas_en_combos { get; set; }
    }
}
