//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_periodo
    {
        public int idempresa { get; set; }
        public int idperiodo { get; set; }
        public int idaniofiscal { get; set; }
        public int pe_mes { get; set; }
        public System.DateTime pe_fechaini { get; set; }
        public System.DateTime pe_fechafin { get; set; }
        public string pe_cerrado { get; set; }
        public string pe_estado { get; set; }
    }
}
