//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_Tipo_costo
    {
        public int IdEmpresa { get; set; }
        public int IdTipo_Costo { get; set; }
        public string nom_tipo_Costo { get; set; }
        public string nom_tipo_Costo2 { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
