//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_retencion_Multiple
    {
        public cxc_retencion_Multiple()
        {
            this.cxc_retencion_Multiple_Documento = new HashSet<cxc_retencion_Multiple_Documento>();
            this.cxc_retencion_Multiple_Documentos_ValorAplicado = new HashSet<cxc_retencion_Multiple_Documentos_ValorAplicado>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdMultir { get; set; }
        public int IdSucursal { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaCobro { get; set; }
        public decimal IdCliente { get; set; }
        public int IdCaja { get; set; }
        public string NumRetencion { get; set; }
        public System.DateTime FechaRetencion { get; set; }
        public double TotalRetencion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<cxc_retencion_Multiple_Documento> cxc_retencion_Multiple_Documento { get; set; }
        public virtual ICollection<cxc_retencion_Multiple_Documentos_ValorAplicado> cxc_retencion_Multiple_Documentos_ValorAplicado { get; set; }
    }
}
