//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_GuiaRemision_Exportacion
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdGuiaRemision { get; set; }
        public string EmbarqueTipo { get; set; }
        public string Ruta { get; set; }
        public string Contenedor { get; set; }
        public string Sello { get; set; }
        public string Vapor { get; set; }
        public string Embalaje { get; set; }
        public double PesoNeto { get; set; }
        public double PesoBruto { get; set; }
        public string Exportador_nombre { get; set; }
        public string Exportador_direccion { get; set; }
        public string Exportador_correo { get; set; }
        public string Exportador_telefono { get; set; }
        public string Exportador_fax { get; set; }
        public string Comprador_nombre { get; set; }
        public string Comprador_direccion { get; set; }
        public string Comprador_correo { get; set; }
        public string Comprador_telefono { get; set; }
        public string Comprador_fax { get; set; }
    
        public virtual in_GuiaRemision in_GuiaRemision { get; set; }
    }
}
