//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Ing_Egr_Inven_det_x_prd_OrdenTrabajo_Det
    {
        public int IdEmpresa_inv { get; set; }
        public int IdSucursal_inv { get; set; }
        public int IdMovi_inven_tipo_inv { get; set; }
        public decimal IdNumMovi_inv { get; set; }
        public int Secuencia_inv { get; set; }
        public int IdEmpresa_ot { get; set; }
        public int IdSucursal_ot { get; set; }
        public decimal IdOrdenTrabajo_ot { get; set; }
        public int Secuencia_ot { get; set; }
    }
}
