//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_producto_precio_historico
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdProducto { get; set; }
        public string IdUsuario { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaTrans { get; set; }
        public Nullable<double> pr_precio_publico { get; set; }
        public Nullable<double> pr_precio_mayor { get; set; }
        public Nullable<double> pr_precio_minimo { get; set; }
    }
}
