//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mail_Attachment
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdMail { get; set; }
        public int Secuencia { get; set; }
        public string nombre { get; set; }
        public byte[] archivo { get; set; }
    
        public virtual mail_Mail mail_Mail { get; set; }
    }
}
