//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesGeneral : DbContext
    {
        public EntitiesGeneral()
            : base("name=EntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_banco> tb_banco { get; set; }
        public DbSet<tb_bodega> tb_bodega { get; set; }
        public DbSet<tb_calendario> tb_calendario { get; set; }
        public DbSet<tb_catalogo> tb_catalogo { get; set; }
        public DbSet<tb_catalogotipo> tb_catalogotipo { get; set; }
        public DbSet<tb_comprobantesrecibidos> tb_comprobantesrecibidos { get; set; }
        public DbSet<tb_conexion_dashboard> tb_conexion_dashboard { get; set; }
        public DbSet<tb_conexion_dbfacturacion_electronica> tb_conexion_dbfacturacion_electronica { get; set; }
        public DbSet<tb_dia> tb_dia { get; set; }
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<tb_mes> tb_mes { get; set; }
        public DbSet<tb_modulo> tb_modulo { get; set; }
        public DbSet<tb_moneda> tb_moneda { get; set; }
        public DbSet<tb_parametro> tb_parametro { get; set; }
        public DbSet<tb_parametro_tipo> tb_parametro_tipo { get; set; }
        public DbSet<tb_persona> tb_persona { get; set; }
        public DbSet<tb_persona_tipo> tb_persona_tipo { get; set; }
        public DbSet<tb_sis_datos_sistema> tb_sis_datos_sistema { get; set; }
        public DbSet<tb_sis_documento_tipo> tb_sis_documento_tipo { get; set; }
        public DbSet<tb_sis_documento_tipo_talonario> tb_sis_documento_tipo_talonario { get; set; }
        public DbSet<tb_sis_documento_tipo_x_empresa> tb_sis_documento_tipo_x_empresa { get; set; }
        public DbSet<tb_sis_impuesto> tb_sis_impuesto { get; set; }
        public DbSet<tb_sis_impuesto_tipo> tb_sis_impuesto_tipo { get; set; }
        public DbSet<tb_sis_impuesto_x_ctacble> tb_sis_impuesto_x_ctacble { get; set; }
        public DbSet<tb_sis_log_error_vzen> tb_sis_log_error_vzen { get; set; }
        public DbSet<tb_sis_mensajes_sys> tb_sis_mensajes_sys { get; set; }
        public DbSet<tb_sis_reporte> tb_sis_reporte { get; set; }
        public DbSet<tb_sucursal> tb_sucursal { get; set; }
        public DbSet<vw_estadocivil> vw_estadocivil { get; set; }
        public DbSet<vw_naturalezapersona> vw_naturalezapersona { get; set; }
        public DbSet<vw_persona> vw_persona { get; set; }
        public DbSet<vw_tipoctabancos> vw_tipoctabancos { get; set; }
        public DbSet<vw_tipodocumento> vw_tipodocumento { get; set; }
        public DbSet<vwtb_bodega_x_sucursal_treelist> vwtb_bodega_x_sucursal_treelist { get; set; }
        public DbSet<vwtb_bodega_x_tb_sucursal> vwtb_bodega_x_tb_sucursal { get; set; }
        public DbSet<vwtb_empresa_x_usuario> vwtb_empresa_x_usuario { get; set; }
        public DbSet<vwtb_persona_beneficiario> vwtb_persona_beneficiario { get; set; }
        public DbSet<vwtb_persona_beneficiario_por_banco_acreditacion> vwtb_persona_beneficiario_por_banco_acreditacion { get; set; }
        public DbSet<vwtb_tb_sis_documento_tipo_talonario> vwtb_tb_sis_documento_tipo_talonario { get; set; }
        public DbSet<vwge_tb_sis_documento_tipo_talonario> vwge_tb_sis_documento_tipo_talonario { get; set; }
    
        public virtual ObjectResult<spSys_ObtenerFecha_SinFeriadoTampocoSabDom_Result> spSys_ObtenerFecha_SinFeriadoTampocoSabDom(Nullable<System.DateTime> p_FechaInicial, Nullable<int> p_Dias)
        {
            var p_FechaInicialParameter = p_FechaInicial.HasValue ?
                new ObjectParameter("p_FechaInicial", p_FechaInicial) :
                new ObjectParameter("p_FechaInicial", typeof(System.DateTime));
    
            var p_DiasParameter = p_Dias.HasValue ?
                new ObjectParameter("p_Dias", p_Dias) :
                new ObjectParameter("p_Dias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSys_ObtenerFecha_SinFeriadoTampocoSabDom_Result>("spSys_ObtenerFecha_SinFeriadoTampocoSabDom", p_FechaInicialParameter, p_DiasParameter);
        }
    
        public virtual ObjectResult<spSys_Ge_Comparativo_Modulo_vs_Contas_Result> spSys_Ge_Comparativo_Modulo_vs_Contas(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_fecha_ini, Nullable<System.DateTime> p_fecha_fin)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_fecha_iniParameter = p_fecha_ini.HasValue ?
                new ObjectParameter("p_fecha_ini", p_fecha_ini) :
                new ObjectParameter("p_fecha_ini", typeof(System.DateTime));
    
            var p_fecha_finParameter = p_fecha_fin.HasValue ?
                new ObjectParameter("p_fecha_fin", p_fecha_fin) :
                new ObjectParameter("p_fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSys_Ge_Comparativo_Modulo_vs_Contas_Result>("spSys_Ge_Comparativo_Modulo_vs_Contas", p_IdEmpresaParameter, p_fecha_iniParameter, p_fecha_finParameter);
        }
    }
}
