//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesDBConta : DbContext
    {
        public EntitiesDBConta()
            : base("name=EntitiesDBConta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ct_anio_fiscal> ct_anio_fiscal { get; set; }
        public DbSet<ct_anio_fiscal_x_cuenta_utilidad> ct_anio_fiscal_x_cuenta_utilidad { get; set; }
        public DbSet<ct_cbtecble> ct_cbtecble { get; set; }
        public DbSet<ct_cbtecble_det> ct_cbtecble_det { get; set; }
        public DbSet<ct_cbtecble_reversado> ct_cbtecble_reversado { get; set; }
        public DbSet<ct_cbtecble_tipo> ct_cbtecble_tipo { get; set; }
        public DbSet<ct_centro_costo> ct_centro_costo { get; set; }
        public DbSet<ct_dashboard_financiero> ct_dashboard_financiero { get; set; }
        public DbSet<ct_grupocble> ct_grupocble { get; set; }
        public DbSet<ct_parametro> ct_parametro { get; set; }
        public DbSet<ct_periodo> ct_periodo { get; set; }
        public DbSet<ct_plancta> ct_plancta { get; set; }
        public DbSet<ct_plancta_nivel> ct_plancta_nivel { get; set; }
        public DbSet<ct_tipo_costo> ct_tipo_costo { get; set; }
        public DbSet<ct_tipo_ctacble> ct_tipo_ctacble { get; set; }
        public DbSet<ct_periodo_x_tb_modulo> ct_periodo_x_tb_modulo { get; set; }
        public DbSet<vwct_anio_fiscal_x_cuenta_utilidad> vwct_anio_fiscal_x_cuenta_utilidad { get; set; }
        public DbSet<vwct_cbtecble_con_ctacble_acreedora> vwct_cbtecble_con_ctacble_acreedora { get; set; }
        public DbSet<vwct_cbtecble_con_saldo> vwct_cbtecble_con_saldo { get; set; }
        public DbSet<vwct_cbtecble_con_saldo_cxp> vwct_cbtecble_con_saldo_cxp { get; set; }
        public DbSet<vwct_cbtecble_con_saldo_cxp_anti_provee> vwct_cbtecble_con_saldo_cxp_anti_provee { get; set; }
        public DbSet<vwct_cbtecble_con_saldo_cxp_consulta> vwct_cbtecble_con_saldo_cxp_consulta { get; set; }
        public DbSet<vwct_cbtecble_con_saldo_cxp_diario> vwct_cbtecble_con_saldo_cxp_diario { get; set; }
        public DbSet<vwct_cbtecble_con_saldo_cxp_nota> vwct_cbtecble_con_saldo_cxp_nota { get; set; }
        public DbSet<vwct_cbtecble_det> vwct_cbtecble_det { get; set; }
        public DbSet<vwct_cbtecble_det_totaldiario> vwct_cbtecble_det_totaldiario { get; set; }
        public DbSet<vwct_centro_costo> vwct_centro_costo { get; set; }
        public DbSet<vwct_comprobantecontable> vwct_comprobantecontable { get; set; }
        public DbSet<vwct_periodo> vwct_periodo { get; set; }
        public DbSet<vwct_plancta> vwct_plancta { get; set; }
        public DbSet<vwct_plancta_nivel> vwct_plancta_nivel { get; set; }
        public DbSet<vwct_saldosxcuentas> vwct_saldosxcuentas { get; set; }
        public DbSet<vwct_utilidadxperiodo> vwct_utilidadxperiodo { get; set; }
        public DbSet<vwct_utilidadxperiodo_saldo_acumulado> vwct_utilidadxperiodo_saldo_acumulado { get; set; }
        public DbSet<vwct_utilidadxperiodo_saldo_anterior> vwct_utilidadxperiodo_saldo_anterior { get; set; }
        public DbSet<vwct_utilidadxperiodo_saldo_periodoactual> vwct_utilidadxperiodo_saldo_periodoactual { get; set; }
    
        public virtual int spCON_Saldo_Inicial_x_cta_cble(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_FechaCorte, string p_IdCentroCosto)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_FechaCorteParameter = p_FechaCorte.HasValue ?
                new ObjectParameter("p_FechaCorte", p_FechaCorte) :
                new ObjectParameter("p_FechaCorte", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCON_Saldo_Inicial_x_cta_cble", p_IdEmpresaParameter, p_FechaCorteParameter, p_IdCentroCostoParameter);
        }
    
        public virtual ObjectResult<spCON_saldo_cuentas_x_anio_para_cierre_Result> spCON_saldo_cuentas_x_anio_para_cierre(Nullable<int> p_IdEmpresa, Nullable<int> p_Anio)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_AnioParameter = p_Anio.HasValue ?
                new ObjectParameter("p_Anio", p_Anio) :
                new ObjectParameter("p_Anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCON_saldo_cuentas_x_anio_para_cierre_Result>("spCON_saldo_cuentas_x_anio_para_cierre", p_IdEmpresaParameter, p_AnioParameter);
        }
    
        public virtual ObjectResult<spCON_Mayorizar_x_fecha_corte_Result> spCON_Mayorizar_x_fecha_corte(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, string p_IdCentroCosto, Nullable<int> p_IdPunto_cargo_grupo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_reg_en_cero, Nullable<bool> p_Mostrar_reg_Centro_costo, Nullable<bool> p_Considerar_Asiento_cierre_anual, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            var p_Mostrar_reg_Centro_costoParameter = p_Mostrar_reg_Centro_costo.HasValue ?
                new ObjectParameter("p_Mostrar_reg_Centro_costo", p_Mostrar_reg_Centro_costo) :
                new ObjectParameter("p_Mostrar_reg_Centro_costo", typeof(bool));
    
            var p_Considerar_Asiento_cierre_anualParameter = p_Considerar_Asiento_cierre_anual.HasValue ?
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", p_Considerar_Asiento_cierre_anual) :
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCON_Mayorizar_x_fecha_corte_Result>("spCON_Mayorizar_x_fecha_corte", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdCentroCostoParameter, p_IdPunto_cargo_grupoParameter, p_IdPunto_cargoParameter, p_Mostrar_reg_en_ceroParameter, p_Mostrar_reg_Centro_costoParameter, p_Considerar_Asiento_cierre_anualParameter, p_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<spCON_Mayorizar_x_Rangofecha_Result> spCON_Mayorizar_x_Rangofecha(Nullable<int> p_IdEmpresa, Nullable<System.DateTime> p_Fecha_Ini, Nullable<System.DateTime> p_Fecha_Fin, string p_IdCentroCosto, Nullable<int> p_IdPunto_cargo_grupo, Nullable<int> p_IdPunto_cargo, Nullable<bool> p_Mostrar_reg_en_cero, Nullable<bool> p_Mostrar_reg_Centro_costo, Nullable<bool> p_Considerar_Asiento_cierre_anual, string p_IdUsuario)
        {
            var p_IdEmpresaParameter = p_IdEmpresa.HasValue ?
                new ObjectParameter("p_IdEmpresa", p_IdEmpresa) :
                new ObjectParameter("p_IdEmpresa", typeof(int));
    
            var p_Fecha_IniParameter = p_Fecha_Ini.HasValue ?
                new ObjectParameter("p_Fecha_Ini", p_Fecha_Ini) :
                new ObjectParameter("p_Fecha_Ini", typeof(System.DateTime));
    
            var p_Fecha_FinParameter = p_Fecha_Fin.HasValue ?
                new ObjectParameter("p_Fecha_Fin", p_Fecha_Fin) :
                new ObjectParameter("p_Fecha_Fin", typeof(System.DateTime));
    
            var p_IdCentroCostoParameter = p_IdCentroCosto != null ?
                new ObjectParameter("p_IdCentroCosto", p_IdCentroCosto) :
                new ObjectParameter("p_IdCentroCosto", typeof(string));
    
            var p_IdPunto_cargo_grupoParameter = p_IdPunto_cargo_grupo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo_grupo", p_IdPunto_cargo_grupo) :
                new ObjectParameter("p_IdPunto_cargo_grupo", typeof(int));
    
            var p_IdPunto_cargoParameter = p_IdPunto_cargo.HasValue ?
                new ObjectParameter("p_IdPunto_cargo", p_IdPunto_cargo) :
                new ObjectParameter("p_IdPunto_cargo", typeof(int));
    
            var p_Mostrar_reg_en_ceroParameter = p_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("p_Mostrar_reg_en_cero", p_Mostrar_reg_en_cero) :
                new ObjectParameter("p_Mostrar_reg_en_cero", typeof(bool));
    
            var p_Mostrar_reg_Centro_costoParameter = p_Mostrar_reg_Centro_costo.HasValue ?
                new ObjectParameter("p_Mostrar_reg_Centro_costo", p_Mostrar_reg_Centro_costo) :
                new ObjectParameter("p_Mostrar_reg_Centro_costo", typeof(bool));
    
            var p_Considerar_Asiento_cierre_anualParameter = p_Considerar_Asiento_cierre_anual.HasValue ?
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", p_Considerar_Asiento_cierre_anual) :
                new ObjectParameter("p_Considerar_Asiento_cierre_anual", typeof(bool));
    
            var p_IdUsuarioParameter = p_IdUsuario != null ?
                new ObjectParameter("p_IdUsuario", p_IdUsuario) :
                new ObjectParameter("p_IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCON_Mayorizar_x_Rangofecha_Result>("spCON_Mayorizar_x_Rangofecha", p_IdEmpresaParameter, p_Fecha_IniParameter, p_Fecha_FinParameter, p_IdCentroCostoParameter, p_IdPunto_cargo_grupoParameter, p_IdPunto_cargoParameter, p_Mostrar_reg_en_ceroParameter, p_Mostrar_reg_Centro_costoParameter, p_Considerar_Asiento_cierre_anualParameter, p_IdUsuarioParameter);
        }
    }
}
