//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesSeguAcceso : DbContext
    {
        public EntitiesSeguAcceso()
            : base("name=EntitiesSeguAcceso")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<seg_menu> seg_menu { get; set; }
        public DbSet<seg_menu_x_empresa_x_usuario> seg_menu_x_empresa_x_usuario { get; set; }
        public DbSet<seg_usuario> seg_usuario { get; set; }
        public DbSet<seg_usuario_x_empresa> seg_usuario_x_empresa { get; set; }
        public DbSet<seg_usuario_x_tb_sis_reporte> seg_usuario_x_tb_sis_reporte { get; set; }
        public DbSet<seg_menu_x_empresa> seg_menu_x_empresa { get; set; }
        public DbSet<vw_seg_menu_x_usuario_x_empresa> vw_seg_menu_x_usuario_x_empresa { get; set; }
        public DbSet<vwseg_menu_x_usuario_x_empresa> vwseg_menu_x_usuario_x_empresa { get; set; }
        public DbSet<vwseg_usuario_x_empresa> vwseg_usuario_x_empresa { get; set; }
        public DbSet<vwseg_usuario_x_tb_sis_reporte> vwseg_usuario_x_tb_sis_reporte { get; set; }
    }
}
