//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_menu
    {
        public int idmenu { get; set; }
        public Nullable<int> idmenupadre { get; set; }
        public string descripcionmenu { get; set; }
        public int posicionmenu { get; set; }
        public bool habilitado { get; set; }
        public bool tiene_formularioasociado { get; set; }
        public string nom_formulario { get; set; }
        public string nom_asembly { get; set; }
        public byte[] imagen_grande { get; set; }
        public byte[] imagen_peque { get; set; }
        public byte[] icono { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
