//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario
    {
        public seg_usuario()
        {
            this.seg_menu_x_empresa_x_usuario = new HashSet<seg_menu_x_empresa_x_usuario>();
            this.seg_usuario_x_empresa = new HashSet<seg_usuario_x_empresa>();
            this.seg_usuario_x_tb_sis_reporte = new HashSet<seg_usuario_x_tb_sis_reporte>();
        }
    
        public string idusuario { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public string idusuarioultmodi { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motivoanulacion { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> exigirdirectivacontrasenia { get; set; }
        public Nullable<bool> cambiarcontraseniasgtsesion { get; set; }
        public Nullable<int> iddepartamento { get; set; }
    
        public virtual ICollection<seg_menu_x_empresa_x_usuario> seg_menu_x_empresa_x_usuario { get; set; }
        public virtual ICollection<seg_usuario_x_empresa> seg_usuario_x_empresa { get; set; }
        public virtual ICollection<seg_usuario_x_tb_sis_reporte> seg_usuario_x_tb_sis_reporte { get; set; }
    }
}
