//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario_x_empresa
    {
        public string idusuario { get; set; }
        public int idempresa { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_usuario seg_usuario { get; set; }
    }
}
