//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario
    {
        public string idusuario { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public string idusuarioultmodi { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motivoanulacion { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> exigirdirectivacontrasenia { get; set; }
        public Nullable<bool> cambiarcontraseniasgtsesion { get; set; }
        public Nullable<int> iddepartamento { get; set; }
    }
}
