//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_menu_x_empresa_x_usuario
    {
        public int idempresa { get; set; }
        public string idusuario { get; set; }
        public int idmenu { get; set; }
        public bool lectura { get; set; }
        public bool escritura { get; set; }
        public bool eliminacion { get; set; }
    }
}
