//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Actividades_Horario_Tipo_Ejecucion
    {
        public tb_Actividades_Horario_Tipo_Ejecucion()
        {
            this.tb_Actividades_Horario = new HashSet<tb_Actividades_Horario>();
        }
    
        public string IdTipoEjecucion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tb_Actividades_Horario> tb_Actividades_Horario { get; set; }
    }
}
