//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bodega
    {
        public int idempresa { get; set; }
        public int idsucursal { get; set; }
        public int idbodega { get; set; }
        public string cod_bodega { get; set; }
        public string bo_descripcion { get; set; }
        public string cod_punto_emision { get; set; }
        public string bo_manejafacturacion { get; set; }
        public string bo_esbodega { get; set; }
        public string idusuario { get; set; }
        public System.DateTime fecha_transac { get; set; }
        public string idusuarioultmod { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string estado { get; set; }
        public string idestadoaproba_x_ing_egr_inven { get; set; }
        public string idcentrocosto { get; set; }
        public string idctactble_inve { get; set; }
        public string idctactble_costo { get; set; }
    }
}
