//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banco
    {
        public int idbanco { get; set; }
        public string ba_descripcion { get; set; }
        public string estado { get; set; }
        public string codigolegal { get; set; }
        public bool tieneformatotransferencia { get; set; }
    }
}
