//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conexion_dashboard
    {
        public int id { get; set; }
        public string provider { get; set; }
        public string servername { get; set; }
        public string portnumber { get; set; }
        public string databasename { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string stringconnection { get; set; }
    }
}
