//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conexion_dbfacturacion_electronica
    {
        public int idempresa { get; set; }
        public string tipo_basedatos { get; set; }
        public string servidor { get; set; }
        public Nullable<int> puerto { get; set; }
        public Nullable<bool> autenticacionwindows { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string nombre_basedatos { get; set; }
        public string cadena_conexion { get; set; }
        public string script_comprobantesrecibidos { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
    }
}
