//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comprobantesrecibidos
    {
        public int id { get; set; }
        public string rucemisor { get; set; }
        public string razonsocialemisor { get; set; }
        public string tipocomprobante { get; set; }
        public string seriecomprobante { get; set; }
        public System.DateTime fechaemision { get; set; }
        public string claveacceso { get; set; }
        public System.DateTime fechaautorizacion { get; set; }
        public string identificacionreceptor { get; set; }
        public Nullable<decimal> valorsinimpuestos { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> importetotal { get; set; }
        public string numerodocumentomodificado { get; set; }
        public string estado { get; set; }
        public string motivo { get; set; }
        public string xml { get; set; }
        public Nullable<int> idempresa_ogiro { get; set; }
        public Nullable<decimal> idcbtecble_ogiro { get; set; }
        public Nullable<int> idtipocbte_ogiro { get; set; }
        public string numeroautorizacion { get; set; }
    }
}
