//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catalogotipo
    {
        public tb_catalogotipo()
        {
            this.tb_catalogo = new HashSet<tb_catalogo>();
        }
    
        public int idtipocatalogo { get; set; }
        public string codigo { get; set; }
        public string tc_descripcion { get; set; }
        public string idusuario { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
        public string idusuarioultmodi { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motivoanulacion { get; set; }
    
        public virtual ICollection<tb_catalogo> tb_catalogo { get; set; }
    }
}
