//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_calendario
    {
        public int idcalendario { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombrefecha { get; set; }
        public string nombrecortofecha { get; set; }
        public Nullable<int> dia_x_semana { get; set; }
        public Nullable<int> dia_x_mes { get; set; }
        public string inicial_del_dia { get; set; }
        public string nombredia { get; set; }
        public Nullable<int> mes_x_anio { get; set; }
        public string nombremes { get; set; }
        public Nullable<int> idmes { get; set; }
        public string nombrecortomes { get; set; }
        public Nullable<int> aniofiscal { get; set; }
        public Nullable<int> semana_x_anio { get; set; }
        public string nombresemana { get; set; }
        public Nullable<int> idsemana { get; set; }
        public Nullable<int> trimestre_x_anio { get; set; }
        public string nombretrimestre { get; set; }
        public Nullable<int> idtrimestre { get; set; }
        public string idperiodo { get; set; }
        public string esferiado { get; set; }
        public string descripcion { get; set; }
    }
}
