//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Conexion_DBFacturacion_Electronica
    {
        public int IdEmpresa { get; set; }
        public string Tipo_BaseDatos { get; set; }
        public string Servidor { get; set; }
        public Nullable<int> Puerto { get; set; }
        public Nullable<bool> AutenticacionWindows { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Nombre_BaseDatos { get; set; }
        public string Cadena_Conexion { get; set; }
        public string Script_ComprobantesRecibidos { get; set; }
    }
}
