//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public int idempresa { get; set; }
        public string codigo { get; set; }
        public string em_nombre { get; set; }
        public string razonsocial { get; set; }
        public string nombrecomercial { get; set; }
        public string contribuyenteespecial { get; set; }
        public string obligadoallevarconta { get; set; }
        public string em_ruc { get; set; }
        public string em_gerente { get; set; }
        public string em_contador { get; set; }
        public string em_ruccontador { get; set; }
        public string em_telefonos { get; set; }
        public string em_fax { get; set; }
        public Nullable<int> em_notificacion { get; set; }
        public string em_direccion { get; set; }
        public string em_tel_int { get; set; }
        public byte[] em_logo { get; set; }
        public byte[] em_fondo { get; set; }
        public System.DateTime em_fechainiciocontable { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> em_fechainicioactividad { get; set; }
        public string cod_entidad_dinardap { get; set; }
        public string em_email { get; set; }
        public string em_email_contacto { get; set; }
        public string sitio_web { get; set; }
    }
}
