//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_persona
    {
        public decimal idpersona { get; set; }
        public string codpersona { get; set; }
        public string pe_naturaleza { get; set; }
        public string pe_nombrecompleto { get; set; }
        public string pe_razonsocial { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public int idtipopersona { get; set; }
        public string idtipodocumento { get; set; }
        public string pe_cedularuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonocasa { get; set; }
        public string pe_telefonoofic { get; set; }
        public string pe_telefonointer { get; set; }
        public string pe_telfono_contacto { get; set; }
        public string pe_celular { get; set; }
        public string pe_correo { get; set; }
        public string pe_fax { get; set; }
        public string pe_casilla { get; set; }
        public string pe_sexo { get; set; }
        public string idestadocivil { get; set; }
        public Nullable<System.DateTime> pe_fechanacimiento { get; set; }
        public string pe_estado { get; set; }
        public Nullable<System.DateTime> pe_fechacreacion { get; set; }
        public Nullable<System.DateTime> pe_fechamodificacion { get; set; }
        public string pe_ultusuariomodi { get; set; }
        public string pe_celularsecundario { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string motivoanulacion { get; set; }
        public string pe_correo_secundario1 { get; set; }
        public string pe_correo_secundario2 { get; set; }
        public string idtipocta_acreditacion_cat { get; set; }
        public string num_cta_acreditacion { get; set; }
        public Nullable<int> idbanco_acreditacion { get; set; }
        public string idtipodocumento_acreditacion { get; set; }
        public string cedularuc_acreditacion { get; set; }
        public string beneficiario_acreditacion { get; set; }
        public string correo_acreditacion { get; set; }
    }
}
