//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_datos_sistema
    {
        public int id { get; set; }
        public string nombre_sistema { get; set; }
        public string version { get; set; }
        public string propietario { get; set; }
        public string desarrolladores { get; set; }
        public string observacion { get; set; }
    }
}
