//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_impuesto
    {
        public string idcod_impuesto { get; set; }
        public string nom_impuesto { get; set; }
        public bool usado_en_ventas { get; set; }
        public bool usado_en_compras { get; set; }
        public double porcentaje { get; set; }
        public Nullable<int> idcodigo_sri { get; set; }
        public bool estado { get; set; }
        public string idtipoimpuesto { get; set; }
    }
}
