//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_impuesto_tipo
    {
        public tb_sis_impuesto_tipo()
        {
            this.tb_sis_impuesto = new HashSet<tb_sis_impuesto>();
        }
    
        public string idtipoimpuesto { get; set; }
        public string nom_tipoimpuesto { get; set; }
    
        public virtual ICollection<tb_sis_impuesto> tb_sis_impuesto { get; set; }
    }
}
