//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_log_error_vzen
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> fecha_trans { get; set; }
        public string detalle { get; set; }
        public string tipo { get; set; }
        public string clase { get; set; }
        public string pantalla { get; set; }
        public string asamble { get; set; }
        public string usuario { get; set; }
        public string ip { get; set; }
        public string pc { get; set; }
    }
}
