//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_documento_tipo_x_empresa
    {
        public int idempresa { get; set; }
        public string coddocumentotipo { get; set; }
        public string aparececombofac_tipofact { get; set; }
        public string aparececombofac_import { get; set; }
        public string aparecetalonario { get; set; }
        public string descripcion { get; set; }
        public int posicion { get; set; }
        public string aparececombo_filereporte { get; set; }
    }
}
