//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_documento_tipo_talonario
    {
        public int idempresa { get; set; }
        public string coddocumentotipo { get; set; }
        public string establecimiento { get; set; }
        public string puntoemision { get; set; }
        public string numdocumento { get; set; }
        public Nullable<System.DateTime> fechacaducidad { get; set; }
        public Nullable<bool> usado { get; set; }
        public string estado { get; set; }
        public int idsucursal { get; set; }
        public string numautorizacion { get; set; }
        public Nullable<bool> es_documento_electronico { get; set; }
    }
}
