//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_reporte
    {
        public string codreporte { get; set; }
        public string nombre { get; set; }
        public string nombrecorto { get; set; }
        public string modulo { get; set; }
        public string vistarpt { get; set; }
        public string formulario { get; set; }
        public string class_nomreporte { get; set; }
        public string nom_asembly { get; set; }
        public int orden { get; set; }
        public string observacion { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> versionactual { get; set; }
        public string tipo_balance { get; set; }
        public string squery { get; set; }
        public string class_info { get; set; }
        public string class_bus { get; set; }
        public string class_data { get; set; }
        public Nullable<int> idgrupo_reporte { get; set; }
        public Nullable<bool> se_muestra_admin_reporte { get; set; }
        public string estado { get; set; }
        public string store_proce_rpt { get; set; }
        public byte[] disenio_reporte { get; set; }
    }
}
