//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sucursal
    {
        public int idempresa { get; set; }
        public int idsucursal { get; set; }
        public string codigo { get; set; }
        public string su_descripcion { get; set; }
        public string su_codigoestablecimiento { get; set; }
        public string su_ubicacion { get; set; }
        public string su_ruc { get; set; }
        public string su_jefesucursal { get; set; }
        public string su_telefonos { get; set; }
        public string su_direccion { get; set; }
        public string idusuario { get; set; }
        public Nullable<System.DateTime> fecha_transac { get; set; }
        public string idusuarioultmod { get; set; }
        public Nullable<System.DateTime> fecha_ultmod { get; set; }
        public string idusuarioultanu { get; set; }
        public Nullable<System.DateTime> fecha_ultanu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string estado { get; set; }
        public string motianula { get; set; }
        public Nullable<bool> es_establecimiento { get; set; }
    }
}
