//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_impuesto
    {
        public tb_sis_impuesto()
        {
            this.tb_sis_impuesto_x_ctacble = new HashSet<tb_sis_impuesto_x_ctacble>();
        }
    
        public string idcod_impuesto { get; set; }
        public string nom_impuesto { get; set; }
        public bool usado_en_ventas { get; set; }
        public bool usado_en_compras { get; set; }
        public double porcentaje { get; set; }
        public Nullable<int> idcodigo_sri { get; set; }
        public bool estado { get; set; }
        public string idtipoimpuesto { get; set; }
    
        public virtual tb_sis_impuesto_tipo tb_sis_impuesto_tipo { get; set; }
        public virtual ICollection<tb_sis_impuesto_x_ctacble> tb_sis_impuesto_x_ctacble { get; set; }
    }
}
