//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarea
    {
        public int IdEmpresa { get; set; }
        public decimal IdTarea { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaIni { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string IdUsuarioUltAsignacion { get; set; }
        public Nullable<System.DateTime> FechaUltAsignacion { get; set; }
        public string EstadoTarea { get; set; }
        public string Estado { get; set; }
        public string Prioridad { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> FechaUltAnu { get; set; }
        public string MotivoAnu { get; set; }
    }
}
