//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_Anticipos_Proveedores
    {
        public int idempresa { get; set; }
        public decimal IdOrdenPago { get; set; }
        public string pr_nombre { get; set; }
        public string Observacion { get; set; }
        public string IdTipo_op { get; set; }
        public Nullable<decimal> IdEntidad { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public string IdFormaPago { get; set; }
        public double Valor_a_pagar { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> IdCbteCble_cxp { get; set; }
        public string Factura { get; set; }
        public double Total_Pagado_Fact { get; set; }
    }
}
