//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_ctacble_acreedora
    {
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public string idctacble_acreedora { get; set; }
    }
}
