//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_plancta_nivel
    {
        public int idempresa { get; set; }
        public int idnivelcta { get; set; }
        public int nv_numdigitos { get; set; }
        public string nv_descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> nv_numdigitos_total { get; set; }
    }
}
