//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_anio_fiscal_x_cuenta_utilidad
    {
        public int idempresa { get; set; }
        public int idaniofiscal { get; set; }
        public string idctacble { get; set; }
        public string pc_cuenta { get; set; }
        public int idnivelcta { get; set; }
        public string idgrupocble { get; set; }
        public string idtipoctacble { get; set; }
        public string gc_grupocble { get; set; }
    }
}
