//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_saldosxcuentas
    {
        public int idempresa { get; set; }
        public int idaniof { get; set; }
        public int idperiodo { get; set; }
        public string idctacble { get; set; }
        public string pc_cuenta { get; set; }
        public string pc_naturaleza { get; set; }
        public long idnivel { get; set; }
        public string idctacblepadre { get; set; }
        public double sc_saldo_anterior { get; set; }
        public double sc_debito_mes { get; set; }
        public double sc_credito_mes { get; set; }
        public double sc_saldoperiodo { get; set; }
        public long sc_debito_acum { get; set; }
        public long sc_credito_acum { get; set; }
        public double sc_saldo_acum { get; set; }
        public string idgrupocble { get; set; }
        public string gc_grupocble { get; set; }
        public long gc_orden { get; set; }
        public string gc_estado_financiero { get; set; }
        public string sidperiodo { get; set; }
    }
}
