//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp_consulta
    {
        public decimal fila { get; set; }
        public Nullable<int> idempresa { get; set; }
        public Nullable<decimal> idcbtecble { get; set; }
        public Nullable<int> idtipocbte { get; set; }
        public System.DateTime cb_fecha { get; set; }
        public string cb_observacion { get; set; }
        public string referencia { get; set; }
        public string tc_tipocbte { get; set; }
        public Nullable<double> valor_cbte { get; set; }
        public double valor_cancelado_cbte { get; set; }
        public Nullable<double> valor_saldo_cbte { get; set; }
        public string tipo { get; set; }
        public decimal idconciliacion { get; set; }
        public string beneficiario { get; set; }
    }
}
