//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp_anti_provee
    {
        public Nullable<int> idempresa { get; set; }
        public Nullable<decimal> idcbtecble { get; set; }
        public Nullable<int> idtipocbte { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
        public string tc_tipocbte { get; set; }
        public double valor_cbte { get; set; }
        public double valor_cancelado { get; set; }
        public double valor_saldo_cbte { get; set; }
        public string tipo { get; set; }
        public int idempresaop { get; set; }
        public decimal idordenpagoop { get; set; }
        public int secuenciaop { get; set; }
        public string idctacble { get; set; }
        public string idctacble_anticipo { get; set; }
        public string beneficiario { get; set; }
        public decimal idproveedor { get; set; }
    }
}
