//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_con_saldo_cxp_nota
    {
        public int idempresa { get; set; }
        public decimal idcbtecble_nota { get; set; }
        public int idtipocbte_nota { get; set; }
        public System.DateTime cn_fecha { get; set; }
        public string cn_observacion { get; set; }
        public string referncia { get; set; }
        public string tc_tipocbte { get; set; }
        public decimal valor_cbte { get; set; }
        public double valor_cancelado_cbte { get; set; }
        public double valor_saldo_cbte { get; set; }
        public string tipo { get; set; }
        public string idctacble { get; set; }
        public string idctaanticipo { get; set; }
        public string beneficiario { get; set; }
        public decimal idproveedor { get; set; }
    }
}
