//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_comprobantecontable
    {
        public double debe { get; set; }
        public double cred { get; set; }
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public string codcbtecble { get; set; }
        public int idperiodo { get; set; }
        public System.DateTime cb_fecha { get; set; }
        public double cb_valor { get; set; }
        public string cb_observacion { get; set; }
        public string cb_estado { get; set; }
        public int cb_anio { get; set; }
        public int cb_mes { get; set; }
        public int secuencia { get; set; }
        public string idctacble { get; set; }
        public double dc_valor { get; set; }
        public string dc_observacion { get; set; }
        public string pc_cuenta { get; set; }
        public string tc_tipocbte { get; set; }
    }
}
