//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_plancta
    {
        public int idempresa { get; set; }
        public string idctacble { get; set; }
        public string pc_cuenta { get; set; }
        public string idctacblepadre { get; set; }
        public Nullable<decimal> idcatalogo { get; set; }
        public string pc_naturaleza { get; set; }
        public int idnivelcta { get; set; }
        public string idgrupocble { get; set; }
        public string pc_estado { get; set; }
        public string pc_esmovimiento { get; set; }
        public string pc_es_flujo_efectivo { get; set; }
        public string pc_clave_corta { get; set; }
        public string cuentapadre { get; set; }
        public string idtipoctacble { get; set; }
        public Nullable<int> idtipo_costo { get; set; }
    }
}
