//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_centro_costo
    {
        public int idempresa { get; set; }
        public string idcentrocosto { get; set; }
        public string codcentrocosto { get; set; }
        public string centro_costo { get; set; }
        public string centro_costopadre { get; set; }
        public string idcentrocostopadre { get; set; }
        public Nullable<decimal> idcatalogo { get; set; }
        public string pc_esmovimiento { get; set; }
        public int idnivel { get; set; }
        public string pc_estado { get; set; }
        public string idctacble { get; set; }
    }
}
