//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_det
    {
        public int idempresa { get; set; }
        public int idtipocbte { get; set; }
        public decimal idcbtecble { get; set; }
        public int idperiodo { get; set; }
        public System.DateTime cb_fecha { get; set; }
        public string cb_observacion { get; set; }
        public string cb_estado { get; set; }
        public int cb_anio { get; set; }
        public int cb_mes { get; set; }
        public string cb_mayorizado { get; set; }
        public long cb_para_conciliar { get; set; }
        public int secuencia { get; set; }
        public string idctacble { get; set; }
        public string idcentrocosto { get; set; }
        public string idcentrocosto_sub_centro_costo { get; set; }
        public double dc_valor { get; set; }
        public Nullable<int> idpunto_cargo { get; set; }
        public Nullable<int> idpunto_cargo_grupo { get; set; }
        public string dc_observacion { get; set; }
    }
}
