//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cobro_x_anticipo_pendientes_de_diario
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public string cr_Codigo { get; set; }
        public string IdCobro_tipo { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public System.DateTime cr_fechaDocu { get; set; }
        public System.DateTime cr_fechaCobro { get; set; }
        public decimal IdCliente { get; set; }
        public double cr_TotalCobro { get; set; }
        public string cr_estado { get; set; }
        public Nullable<double> Total_cobro_det { get; set; }
        public Nullable<double> diferencia { get; set; }
        public double valor_cbte { get; set; }
        public double valor_cbte_Positivo { get; set; }
        public string IdCtaCble_cxc { get; set; }
        public string IdCtaCble_Anti { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string cr_observacion { get; set; }
        public string cb_Estado { get; set; }
        public double cb_Valor { get; set; }
    }
}
