//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_costo_producto_vendido
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbte { get; set; }
        public decimal IdCliente { get; set; }
        public double vt_cantidad { get; set; }
        public double vt_Precio { get; set; }
        public Nullable<double> vt_Peso { get; set; }
        public Nullable<double> vt_peso_total { get; set; }
        public double mv_costo { get; set; }
        public double vt_costo_total { get; set; }
        public double vt_venta_bruta { get; set; }
        public double vt_venta_neta { get; set; }
        public double vt_DescUnitario { get; set; }
        public double vt_PorDescUnitario { get; set; }
        public double vt_Subtotal { get; set; }
        public double vt_iva { get; set; }
        public double vt_por_iva { get; set; }
        public double vt_total { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal IdProducto { get; set; }
        public int IdMarca { get; set; }
        public string marca { get; set; }
        public int IdGrupo { get; set; }
        public string nom_grupo { get; set; }
    }
}
