//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Ing_Egr_Inven_x_prd_OrdenTaller_x_Ing_Egr_Inven_Det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public string signo { get; set; }
        public string CodMoviInven { get; set; }
        public string cm_observacion { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public string IdUsuario { get; set; }
        public string Estado { get; set; }
        public string IdCentroCosto { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string nom_bodega { get; set; }
        public string cod_tipo_inv { get; set; }
        public string nom_tipo_inv { get; set; }
        public string signo_tipo_inv { get; set; }
        public Nullable<int> IdMotivo_Inv { get; set; }
        public string IdEstadoAproba { get; set; }
        public string nom_EstadoAproba { get; set; }
        public string Desc_mov_inv { get; set; }
        public string IdEstadoDespacho_cat { get; set; }
        public decimal IdOrdenTaller_OT { get; set; }
        public int Secuencia_OT { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public double pr_peso { get; set; }
        public Nullable<double> PesoEspecifico { get; set; }
        public double CantidadLiberada_OT { get; set; }
        public double PesoUnitario_OT { get; set; }
        public double PesoTotal_Liberado { get; set; }
        public int Secuencia_inv { get; set; }
    }
}
