//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_sis_Documento_Tipo_x_Empresa_Anulados
    {
        public decimal IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<long> anio { get; set; }
        public Nullable<long> mes { get; set; }
        public string CodDocumentoTipo { get; set; }
        public string serie1 { get; set; }
        public string serie2 { get; set; }
        public string NumRetencion { get; set; }
        public string Documento_ini { get; set; }
        public string Documento_fin { get; set; }
        public string NumAutorizacion { get; set; }
        public string Estado { get; set; }
    }
}
