//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_tb_sis_documento_tipo_talonario
    {
        public int idempresa { get; set; }
        public string em_ruc { get; set; }
        public string coddocumentotipo { get; set; }
        public string establecimiento { get; set; }
        public string puntoemision { get; set; }
        public string numdocumento { get; set; }
    }
}
