//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_bodega_x_sucursal_treelist
    {
        public int idempresa { get; set; }
        public string id { get; set; }
        public string idpadre { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public long nivel { get; set; }
        public int idsucursal { get; set; }
        public Nullable<int> idbodega { get; set; }
    }
}
