//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_bodega_x_tb_sucursal
    {
        public int idempresa { get; set; }
        public int idsucursal { get; set; }
        public int idbodega { get; set; }
        public string cod_sucursal { get; set; }
        public string cod_bodega { get; set; }
        public string su_descripcion { get; set; }
        public string bo_descripcion { get; set; }
    }
}
