//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizu.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_persona_beneficiario
    {
        public int idempresa { get; set; }
        public string idbeneficiario { get; set; }
        public string idtipo_persona { get; set; }
        public decimal idpersona { get; set; }
        public decimal identidad { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string pr_girar_cheque_a { get; set; }
        public string pe_razonsocial { get; set; }
        public string pe_cedularuc { get; set; }
        public string pe_naturaleza { get; set; }
        public string idctacble { get; set; }
        public string idctacble_anticipo { get; set; }
        public string idctacble_gasto { get; set; }
        public string estado { get; set; }
        public string idtipocta_acreditacion_cat { get; set; }
        public string num_cta_acreditacion { get; set; }
        public Nullable<int> idbanco_acreditacion { get; set; }
        public string idtipodocumento_acreditacion { get; set; }
        public string cedularuc_acreditacion { get; set; }
        public string beneficiario_acreditacion { get; set; }
        public string correo_acreditacion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_nombrecompleto { get; set; }
        public string idtipodocumento { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonocasa { get; set; }
        public string pe_celular { get; set; }
        public string pe_correo { get; set; }
    }
}
