//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dazzsoft.ERP.Infrastructure.Model.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Cbte_Ban_varios
    {
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPago { get; set; }
        public string Observacion { get; set; }
        public string IdTipo_op { get; set; }
        public string IdTipo_Persona { get; set; }
        public decimal IdPersona { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdEntidad { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public int IdEmpresa_ban { get; set; }
        public decimal IdCbteCble_ban { get; set; }
        public int IdTipocbte_ban { get; set; }
        public double Valor_a_pagar { get; set; }
    }
}
